# Title


### Purpose

State the purpose of the notebook.

### Results

Describe and comment the most important results.

#### Note: how to find location of template file used to auto-generate notebook

```python
import jupytemplate
print(jupytemplate.get_template_path())
```

* after editing the `template.ipynb`, copy it to the path indicated
* `$ jupyter nbextension install --py jupytemplate --sys-prefix`
* `$ jupyter nbextension enable jupytemplate/main --sys-prefix`

## Setup

### Library import
Import required Python libraries

In [1]:
from time import time, asctime, gmtime, localtime
print(asctime(localtime()))

t0 = time()

# from platform import node
# import io
import requests
import os
from os.path import exists
from copy import deepcopy
# import shutil
# from glob import glob
from random import random
# from collections import Counter, OrderedDict
# import gc		# garbage collection module
# import descartes
from pathlib import Path
# import pprint
# import pickle
# import timeit
import sys
from urllib.request import urlopen

print("Python version: ", sys.version_info[:])
print("Un-versioned imports:\n")
prefixStr = ''
if 'collections' in sys.modules:
    print(prefixStr + 'collections', end="")
    prefixStr = ', '
if 'copy' in sys.modules:
    print(prefixStr + 'copy', end="")
    prefixStr = ', '
if 'descartes' in sys.modules:
    print(prefixStr + 'descartes', end="")
    prefixStr = ', '
if 'gc' in sys.modules:
    print(prefixStr + 'gc', end="")
    prefixStr = ', '
if 'glob' in sys.modules:
    print(prefixStr + 'glob', end="")
    prefixStr = ', '
if 'io' in sys.modules:
    print(prefixStr + 'io', end="")
    prefixStr = ', '
if 'pathlib' in sys.modules:
    print(prefixStr + 'pathlib', end="")
    prefixStr = ', '
if 'pickle' in sys.modules:
    print(prefixStr + 'pickle', end="")
    prefixStr = ', '
if 'platform' in sys.modules:
    print(prefixStr + 'platform', end="")
    prefixStr = ', '
if 'plotHelpers' in sys.modules:
    print(prefixStr + 'plotHelpers', end="")
    prefixStr = ', '
if 'pprint' in sys.modules:
    print(prefixStr + 'pprint', end="")
    prefixStr = ', '
if 'os' in sys.modules:
    print(prefixStr + 'os', end="")
    prefixStr = ', '
if 'os.path' in sys.modules:
    print(prefixStr + 'os.path', end="")
    prefixStr = ', '
if 'random' in sys.modules:
    print(prefixStr + 'random', end="")
    prefixStr = ', '
if 'shutil' in sys.modules:
    print(prefixStr + 'shutil', end="")
    prefixStr = ', '
if 'sys' in sys.modules:
    print(prefixStr + 'sys', end="")
    prefixStr = ', '
if 'timeit' in sys.modules:
    print(prefixStr + 'timeit', end="")
    prefixStr = ', '
if 'utility' in sys.modules:
    print(prefixStr + 'utility', end="")
    # prefixStr = ', '

duVersion = None
from dateutil import __version__ as duVersion
from dateutil.parser import parse
import urllib3

import numpy as np

mdVersion = None
# from modin import __version__ as mdVersion
# import modin.pandas as pd
import pandas as pd
ppVersion = None
# from pandas_profiling import ProfileReport
# from pandas_profiling import __version__ as ppVersion

import pyreadr
import pydot_ng
import graphviz

# import requests

gpdVersion = None
# from geopandas import __version__ as gpdVersion
# import geopandas as gpd

shpVersion = None
from shapely import __version__ as shpVersion
from shapely.geometry import Point

scVersion = None
from scipy import __version__ as scVersion
import scipy.sparse as sp

skVersion = None
# from sklearn import __version__ as skVersion
# from sklearn.feature_extraction import text
# from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.feature_selection import chi2
# from sklearn.linear_model import LogisticRegression
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import cross_val_score
# from sklearn.metrics import confusion_matrix
# from sklearn.model_selection import train_test_split
# from sklearn import metrics
# from sklearn.svm import LinearSVC, SVC
# from sklearn.naive_bayes import ComplementNB
# from sklearn.utils import class_weight

tfVersion = None
# from tensorflow import __version__ as tfVersion
# from tensorflow.keras.preprocessing.text import Tokenizer
# from tensorflow.keras.preprocessing.sequence import pad_sequences
# from tensorflow.keras import Input
# from tensorflow.keras.layers import Dense, Embedding, Bidirectional, LSTM, concatenate
# from tensorflow.keras.models import Model
# from tensorflow.keras.callbacks import ModelCheckpoint, TensorBoard
# from tensorflow.keras.utils import plot_model

jlVersion = None
# from joblib import __version__ as jlVersion
# from joblib import dump, load

# Visualizations

mpVersion = None
from matplotlib import __version__ as mpVersion
import matplotlib.pyplot as plt

plVersion = None
from plotly import __version__ as plVersion
import chart_studio.plotly as py
from plotly.subplots import make_subplots
import plotly.graph_objs as go
import plotly.express as px
# import plotly.offline as ply
# plotly.offline.init_notebook_mode(connected=True)
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import cufflinks as cf
# cf.go_offline(connected=True)
cf.set_config_file(theme='white')
cf.set_config_file(offline=True)

import seaborn as sns
import colorcet as cc

print("\n")
if 'colorcet' in sys.modules:
    print(f"colorcet: {cc.__version__}", end="\t")
if 'cufflinks' in sys.modules:
    print(f"cufflinks: {cf.__version__}", end="\t")
if 'dateutil' in sys.modules:
    print(f"dateutil: {duVersion}", end="\t")
if 'geopandas' in sys.modules:
    print(f"geopandas: {gpdVersion}", end="\t")
if 'graphviz' in sys.modules:
    print(f"graphviz: {duVersion}", end="\t")
if 'joblib' in sys.modules:
    print(f"joblib: {jlVersion}", end="\t")
if 'matplotlib' in sys.modules:
    print(f"matplotlib: {mpVersion}", end="\t")
if 'modin' in sys.modules:
    print(f"modin: {mdVersion}", end="\t")
if 'numpy' in sys.modules:
    print(f"numpy: {np.__version__}", end="\t")
if 'pandas' in sys.modules:
    print(f"pandas: {pd.__version__}", end="\t")
if 'pandas_profiling' in sys.modules:
    print(f"pandas_profiling: {ppVersion}", end="\t")
if 'plotly' in sys.modules:
    print(f"plotly: {plVersion}", end="\t")
if 'pydot' in sys.modules:
    print(f"pydot: {pd.__version__}", end="\t")
if 'pyreader' in sys.modules:
    print(f"pyreader: {pyreader.__version__}", end="\t")
if 'requests' in sys.modules:
    print(f"requests: {requests.__version__}", end="\t")
if 'scipy' in sys.modules:
    print(f"scipy: {scVersion}", end="\t")
if 'seaborn' in sys.modules:
    print(f"seaborn: {sns.__version__}", end="\t")
if 'shapely' in sys.modules:
    print(f"shapely: {shpVersion}", end="\t")
if 'sklearn' in sys.modules:
    print(f"sklearn: {skVersion}", end="\t")
if 'tensorflow' in sys.modules:
    print(f"tensorflow: {tfVersion}", end="\t")
if 'urllib3' in sys.modules:
    print(f"urllib3: {urllib3.__version__}", end="\t")
Δt = time() - t0
print(f"\n\nΔt: {Δt: 4.1f}s.")

%matplotlib inline

# Options for pandas
pd.options.display.max_columns = 30
pd.options.display.max_rows = 50

# Autoreload extension
if 'autoreload' not in get_ipython().extension_manager.loaded:
    %load_ext autoreload
    
%autoreload 2

Tue Oct 27 20:33:03 2020
Python version:  (3, 6, 9, 'final', 0)
Un-versioned imports:

collections, copy, gc, glob, io, pathlib, pickle, platform, pprint, os, os.path, random, shutil, sys, timeit



colorcet: 1.0.0	cufflinks: 0.17.3	dateutil: 2.8.1	geopandas: None	graphviz: 2.8.1	matplotlib: 3.3.0	numpy: 1.18.1	pandas: 1.1.3	plotly: 4.11.0	requests: 2.23.0	scipy: 1.4.1	seaborn: 0.11.0	shapely: 1.7.0	urllib3: 1.24.3	

Δt:  1.4s.


### Local library import
Import all required local libraries

In [2]:
# Include local library paths
# sys.path.append('/home/mark/work/Mllib') # uncomment and fill to import local libraries
# Import local libraries
# from utility import DataSci as util
# from utility import symSpellPlus as ssp
# from utility import KerasEarlyStopCallback as esCallback
# from plotHelpers import plotHelpers as ph

**Next two lines are for pretty output for all prints in a Pandas cell, not just the last**

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Helper function

#### `choroplethCovidUSA()`

Creates choropleths from data in df, using plotly geojson formatted county shapes.

Modeled after Plotly's [Choropleth map using GeoJSON](https://plotly.com/python/choropleth-maps/)

In [4]:
def choroplethCovidUSA(df, GeoJSON,
                       decimalRange=[-1, 5],
                       topOfRange=300000,
                       linearRange=None,
                       animationVar=None,
                       locs='fips',
                       colscaleVar='log10cases',
                       colscale='Portland',
                       scope='usa',
                       zlabel='Total cases',
                       hoverDescription='log10(cases)',
                       hoverVar='cases',
                       title='Covid-19 Total Cases to Date'):
    """
    INPUT:
        df					pd.DataFrame, containing data to be plotted
        GeoJSON				plotly shape file dict containing county shapes
        decimalRange		list type(int), containing decimal orders of magnitude
                            for color bar range. (E.g., [-1, 3] for 0.1–1000.),
                            set to None if using linearRange, default: [-1, 5]
        topOfRange			float, containing 'extra' range on top of decimal scale.
                            (E.g. 2500 to extend decimalRange by less than an order
                            of magnitude.) If None, entire range will be specified
                            by decimalRange (or linearRange), default: 25000
        linearRange			list(type=int|float), if not None, fix range of color-
                            bar using linear scale, e.g., [0, 200], default: None.
                            If not None, overrides decimalRange and topOfRange.
        animationVar		str, feature to use to select individual animation
                            frames (typically a time-based variable, such as
                            'weekStr'). If None, no animation, which is the default.
        locs				str, feature used to select shapes from GeoJSON dict,
                            default: 'fips'
        colscaleVar		str, column name in df for z-scale, default: 'log10cases'.
        colscale			str, valid Plotly color scale name, default: 'Portland'
        scope				str, identifier for geographic range, default: 'usa'
        zlabel			str, label on top of color bar
        hoverDescription	str, label, in addition to locs, to describe values in
                            DataFrame column used for colorbar intensity, default:
                            'Total cases'
        hoverVar			str, feature values to be shown when hovering over a
                            region.
        title				str, figure title, default: "Covid-19 Total Cases to Date"
    """

    minval = df[colscaleVar].replace(0, np.nan).min()
    maxval = np.max(df[colscaleVar])
    print(f"minval: {minval}, maxval: {maxval}")

    if linearRange is not None:
        bottomOfRange = linearRange[0]
        topOfRange = linearRange[-1]
    else:
        bottomOfRange = 10**decimalRange[0]
    if maxval > topOfRange:
        print("WARNING: maximum value exceeds top of your range."
              f" {maxval} > {topOfRange}.")
    if minval < bottomOfRange:
        print("WARNING: minimum value is below bottom of your range."
              f" {minval} < {bottomOfRange}.")

    if linearRange is not None:
        tickVals = [round(lv, 4) for lv in linearRange]
        colorAxisVals = [str(lv) for lv in tickVals]
    else:
        linVals = np.logspace(decimalRange[0], decimalRange[1],
                              int(decimalRange[1] - decimalRange[0]) + 1)
        if topOfRange is not None:
            linVals = np.append(linVals, topOfRange)
        linVals = [round(lv, 4) for lv in linVals]
        tickVals = [round(lv, 4) for lv in np.log10(linVals)]

        # coloraxis_colorbar dict needs ticktext to an array of strings:
        colorAxisVals = [str(lv) for lv in linVals]
    print(colorAxisVals)
    print(tickVals)

    fig = px.choropleth(df,
                        animation_frame=animationVar,
                        geojson=GeoJSON,
                        locations=locs,
                        color=colscaleVar,
                        color_continuous_scale=colscale,
                        range_color=(tickVals[0], tickVals[-1]),
                        scope=scope,
                        hover_name=hoverVar,
                        labels={colscaleVar: hoverDescription}
                       )
    fig.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0},
                      title={'text': title,
                             'x': 0.5, 'xanchor': 'center',
                             'y': 0.97, 'yanchor': 'top'},
                      coloraxis_colorbar=dict(title=zlabel,
                                              tickvals=tickVals,
                                              ticktext=colorAxisVals)
                     )
    fig.update_traces(marker_line_width=0.5, marker_opacity=1.0)
    fig.update_geos(showsubunits=True, subunitcolor="black")

    # fig.show("notebook")

    return fig

### Get county shape files to be used by plotly.express

#### Get JSON file from plotly github repo

* if first time, fetch and save to disk
* else, read file from disk

In [5]:
basePath = Path.cwd()
dataPath = basePath.parent / 'data'
commonDataPath = basePath.parent.parent / 'commonData'
countyShapesFile = commonDataPath / 'UScountyShapes.json'
if countyShapesFile.is_file():
    with open(countyShapesFile, 'r') as shapesHandle:
        counties = json.load(shapesHandle)
else:
    URL = 'https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json'
    with urlopen(URL) as response:
        counties = json.load(response)
    with open(countyShapesFile, 'w') as outFile:
        json.dump(counties, outFile)

In [6]:
# counties["features"][1]
for feature in counties["features"]:
    # if (feature['properties']['STATE'] == '29') & (feature['properties']['NAME'] == 'Joplin'):
    if (feature['properties']['STATE'] == '29'): # & (feature['properties']['COUNTY'] == '29-37592'):
        print(feature['properties']['COUNTY'], feature['properties']['NAME'])

097 Jasper
103 Knox
109 Lawrence
117 Livingston
131 Miller
137 Monroe
151 Osage
159 Pettis
169 Pulaski
179 Reynolds
195 Saline
205 Shelby
211 Sullivan
221 Washington
229 Wright
001 Adair
009 Barry
021 Buchanan
033 Carroll
043 Christian
053 Cooper
065 Dent
075 Gentry
085 Hickory
007 Audrain
017 Bollinger
023 Butler
029 Camden
035 Carter
041 Chariton
045 Clark
047 Clay
051 Cole
055 Crawford
057 Dade
061 Daviess
067 Douglas
073 Gasconade
077 Greene
079 Grundy
087 Holt
105 Laclede
111 Lewis
119 McDonald
125 Maries
129 Mercer
139 Montgomery
141 Morgan
147 Nodaway
153 Ozark
157 Perry
161 Phelps
167 Polk
171 Putnam
175 Randolph
177 Ray
181 Ripley
186 Ste. Genevieve
187 St. Francois
197 Schuyler
203 Shannon
207 Stoddard
213 Taney
219 Warren
225 Webster
510 St. Louis
095 Jackson
099 Jefferson
115 Linn
121 Macon
135 Moniteau
145 Newton
163 Pike
173 Ralls
185 St. Clair
201 Scott
215 Texas
223 Wayne
003 Andrew
015 Benton
027 Callaway
039 Cedar
049 Clinton
059 Dallas
071 Franklin
083 Henry
093 Iron

## Prepare Data

### Data import

* Data are from the *NY Times* Covid-19 data repository
* Want to use freshest data, so each time this notebook is run the data are downloaded directly from the repo
* pandas v1.x does permit direct reads of remote data using `.read_csv(URL)`, but this fails if any of the many lines in the file have incorrect formatting. In such cases:
  * download the data first
  * manually correct dodgy lines
  * read in the data directly from disk

**As of 10 Oct 2020, modin's .read_csv() does not support direct reading of data from URLs. In order to use modin, download the data files first, and then read them in from file**

In [7]:
URL = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
covidData = requests.get(URL).content

with open(dataPath / 'CovidRaw.csv', 'wb') as source:
    source.write(covidData)

26975900

In [8]:
# df0 = pd.read_csv(URL)
df0 = pd.read_csv(dataPath / 'CovidRaw.csv')
df0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670636 entries, 0 to 670635
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   date    670636 non-null  object 
 1   county  670636 non-null  object 
 2   state   670636 non-null  object 
 3   fips    664204 non-null  float64
 4   cases   670636 non-null  int64  
 5   deaths  670636 non-null  int64  
dtypes: float64(1), int64(2), object(3)
memory usage: 30.7+ MB


#### Get the most recent day's data:

In [9]:
URL = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/live/us-counties.csv"
covidData = requests.get(URL).content
with open(dataPath / 'CovidRawToday.csv', 'wb') as source:
    source.write(covidData)

162384

In [10]:
# df1 = pd.read_csv(URL)
df1 = pd.read_csv(dataPath / 'CovidRawToday.csv')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3242 entries, 0 to 3241
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   date              3242 non-null   object 
 1   county            3242 non-null   object 
 2   state             3242 non-null   object 
 3   fips              3215 non-null   float64
 4   cases             3242 non-null   int64  
 5   deaths            3163 non-null   float64
 6   confirmed_cases   2494 non-null   float64
 7   confirmed_deaths  2027 non-null   float64
 8   probable_cases    1469 non-null   float64
 9   probable_deaths   840 non-null    float64
dtypes: float64(6), int64(1), object(3)
memory usage: 253.4+ KB


### Union data and get aggregate statistics

* After the union, set the date column to datetimes.

In [11]:
df2 = pd.concat([df0, df1]).reset_index(drop=True)

df2['date'] = pd.to_datetime(df2.date)
df2.info()
df2.describe(percentiles=[0.01, 0.05, 0.20, 0.50, 0.80, 0.95, 0.99])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 673878 entries, 0 to 673877
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype         
---  ------            --------------   -----         
 0   date              673878 non-null  datetime64[ns]
 1   county            673878 non-null  object        
 2   state             673878 non-null  object        
 3   fips              667419 non-null  float64       
 4   cases             673878 non-null  int64         
 5   deaths            673799 non-null  float64       
 6   confirmed_cases   2494 non-null    float64       
 7   confirmed_deaths  2027 non-null    float64       
 8   probable_cases    1469 non-null    float64       
 9   probable_deaths   840 non-null     float64       
dtypes: datetime64[ns](1), float64(6), int64(1), object(2)
memory usage: 51.4+ MB


fips          cases         deaths  confirmed_cases  \
count  667419.000000  673878.000000  673799.000000      2494.000000   
mean    31193.924746    1225.856720      42.223623      2673.800722   
std     16274.103993    7046.777377     421.572519     11018.756400   
min      1001.000000       0.000000       0.000000         0.000000   
1%       1061.000000       1.000000       0.000000         6.930000   
5%       5101.000000       2.000000       0.000000        40.650000   
20%     17065.000000      13.000000       0.000000       161.000000   
50%     29199.000000     115.000000       2.000000       573.000000   
80%     48087.000000     762.000000      18.000000      2174.400000   
95%     55013.000000    4591.000000     124.000000     11179.800000   
99%     72085.000000   19036.230000     768.000000     32917.450000   
max     78030.000000  302077.000000   23978.000000    302077.000000   

       confirmed_deaths  probable_cases  probable_deaths  
count       2027.000000     1469.000000       840.000000  
mean          86.147015      195.504425        15.907143  
std          524.837497      778.409432       164.550758  
min            0.000000        0.000000         0.000000  
1%             0.000000        0.000000         0.000000  
5%             0.000000        0.000000         0.000000  
20%            2.000000        6.000000         0.000000  
50%           12.000000       39.000000         1.000000  
80%           58.000000      185.000000         7.000000  
95%          321.500000      700.200000        51.100000  
99%         1245.700000     2720.120000       194.590000  
max        19321.000000    20147.000000      4657.000000

In [12]:
df2.head(10)

date       county       state     fips  cases  deaths  \
0 2020-01-21    Snohomish  Washington  53061.0      1     0.0   
1 2020-01-22    Snohomish  Washington  53061.0      1     0.0   
2 2020-01-23    Snohomish  Washington  53061.0      1     0.0   
3 2020-01-24         Cook    Illinois  17031.0      1     0.0   
4 2020-01-24    Snohomish  Washington  53061.0      1     0.0   
5 2020-01-25       Orange  California   6059.0      1     0.0   
6 2020-01-25         Cook    Illinois  17031.0      1     0.0   
7 2020-01-25    Snohomish  Washington  53061.0      1     0.0   
8 2020-01-26     Maricopa     Arizona   4013.0      1     0.0   
9 2020-01-26  Los Angeles  California   6037.0      1     0.0   

   confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
0              NaN               NaN             NaN              NaN  
1              NaN               NaN             NaN              NaN  
2              NaN               NaN             NaN              NaN  
3              NaN               NaN             NaN              NaN  
4              NaN               NaN             NaN              NaN  
5              NaN               NaN             NaN              NaN  
6              NaN               NaN             NaN              NaN  
7              NaN               NaN             NaN              NaN  
8              NaN               NaN             NaN              NaN  
9              NaN               NaN             NaN              NaN

In [13]:
df2.tail(10)

date      county    state     fips  cases  deaths  \
673868 2020-10-27    Niobrara  Wyoming  56027.0     12     0.0   
673869 2020-10-27        Park  Wyoming  56029.0    628     3.0   
673870 2020-10-27      Platte  Wyoming  56031.0    127     2.0   
673871 2020-10-27    Sheridan  Wyoming  56033.0    721     4.0   
673872 2020-10-27    Sublette  Wyoming  56035.0    160     1.0   
673873 2020-10-27  Sweetwater  Wyoming  56037.0    488     2.0   
673874 2020-10-27       Teton  Wyoming  56039.0    761     1.0   
673875 2020-10-27       Uinta  Wyoming  56041.0    451     3.0   
673876 2020-10-27    Washakie  Wyoming  56043.0    150     7.0   
673877 2020-10-27      Weston  Wyoming  56045.0    139     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
673868              4.0               NaN             8.0              NaN  
673869            563.0               NaN            65.0              NaN  
673870             84.0               NaN            43.0              NaN  
673871            555.0               NaN           166.0              NaN  
673872            122.0               NaN            38.0              NaN  
673873            461.0               NaN            27.0              NaN  
673874            728.0               NaN            33.0              NaN  
673875            362.0               NaN            89.0              NaN  
673876            138.0               NaN            12.0              NaN  
673877            109.0               NaN            30.0              NaN

### Get fips values

#### By county

In [14]:
dffc = pd.read_csv(commonDataPath / 'nrcsFIPS.tsv', delimiter='\t')
dffc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3232 entries, 0 to 3231
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   FIPS       3232 non-null   int64 
 1   County     3232 non-null   object
 2   StateCode  3232 non-null   object
dtypes: int64(1), object(2)
memory usage: 75.9+ KB


In [15]:
dffc.head(9)
dffc.tail(9)

FIPS    County StateCode
0  1001   Autauga        AL
1  1003   Baldwin        AL
2  1005   Barbour        AL
3  1007      Bibb        AL
4  1009    Blount        AL
5  1011   Bullock        AL
6  1013    Butler        AL
7  1015   Calhoun        AL
8  1017  Chambers        AL

FIPS      County StateCode
3223  72143   Vega Alta        PR
3224  72145   Vega Baja        PR
3225  72147     Vieques        PR
3226  72149    Villalba        PR
3227  72151     Yabucoa        PR
3228  72153       Yauco        PR
3229  78010   St. Croix        VI
3230  78020    St. John        VI
3231  78030  St. Thomas        VI

#### By state

In [16]:
dffs = pd.read_csv(commonDataPath / 'nrcsStateFIPS.tsv', delimiter='\t')
dffs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   State      55 non-null     object
 1   StateCode  55 non-null     object
 2   StateFIPS  55 non-null     int64 
dtypes: int64(1), object(2)
memory usage: 1.4+ KB


In [17]:
dffs.head()
dffs.tail()

State StateCode  StateFIPS
0     Alabama        AL          1
1      Alaska        AK          2
2     Arizona        AZ          4
3    Arkansas        AR          5
4  California        CA          6

State StateCode  StateFIPS
50            American Samoa        AS         60
51                      Guam        GU         66
52  Northern Mariana Islands        MP         69
53               Puerto Rico        PR         72
54            Virgin Islands        VI         78

##### Create a State ⟶ StateCode dict

This is used in [Replace 'Unknown' counties with StateCode-Unknown values](#Replace-'Unknown'-counties-with-StateCode-Unknown-values)

In [18]:
State2StateCode = {s: sc for s, sc in zip(dffs.State, dffs.StateCode)}
State2StateCode

{'Alabama': 'AL',
 'Alaska': 'AK',
 'Arizona': 'AZ',
 'Arkansas': 'AR',
 'California': 'CA',
 'Colorado': 'CO',
 'Connecticut': 'CT',
 'Delaware': 'DE',
 'Florida': 'FL',
 'Georgia': 'GA',
 'Hawaii': 'HI',
 'Idaho': 'ID',
 'Illinois': 'IL',
 'Indiana': 'IN',
 'Iowa': 'IA',
 'Kansas': 'KS',
 'Kentucky': 'KY',
 'Louisiana': 'LA',
 'Maine': 'ME',
 'Maryland': 'MD',
 'Massachusetts': 'MA',
 'Michigan': 'MI',
 'Minnesota': 'MN',
 'Mississippi': 'MS',
 'Missouri': 'MO',
 'Montana': 'MT',
 'Nebraska': 'NE',
 'Nevada': 'NV',
 'New Hampshire': 'NH',
 'New Jersey': 'NJ',
 'New Mexico': 'NM',
 'New York': 'NY',
 'North Carolina': 'NC',
 'North Dakota': 'ND',
 'Ohio': 'OH',
 'Oklahoma': 'OK',
 'Oregon': 'OR',
 'Pennsylvania': 'PA',
 'Rhode Island': 'RI',
 'South Carolina': 'SC',
 'South Dakota': 'SD',
 'Tennessee': 'TN',
 'Texas': 'TX',
 'Utah': 'UT',
 'Vermont': 'VT',
 'Virginia': 'VA',
 'Washington': 'WA',
 'West Virginia': 'WV',
 'Wisconsin': 'WI',
 'Wyoming': 'WY',
 'American Samoa': 'AS',
 'G

**There is no state with FIPS code 11, corresponding to Warshington, D.C.**

In [19]:
dffs[dffs.StateFIPS == 11]

Empty DataFrame
Columns: [State, StateCode, StateFIPS]
Index: []

#### Create dict for state "Unknown"  FIPS codes

* Take the two-digit state code and add 999
* The FIPS code for the 'county' District of Columbia, 11, is missing and needs to be added after creating the dict

In [20]:
stateFIPS = {s: str(f) + '999' for s, f in zip(dffs.State, dffs.StateFIPS)}
stateFIPS['District of Columbia'] = '11999'
sorted(stateFIPS.items(), key=lambda kv: kv[1])
print(stateFIPS)

[('Delaware', '10999'),
 ('District of Columbia', '11999'),
 ('Florida', '12999'),
 ('Georgia', '13999'),
 ('Hawaii', '15999'),
 ('Idaho', '16999'),
 ('Illinois', '17999'),
 ('Indiana', '18999'),
 ('Alabama', '1999'),
 ('Iowa', '19999'),
 ('Kansas', '20999'),
 ('Kentucky', '21999'),
 ('Louisiana', '22999'),
 ('Maine', '23999'),
 ('Maryland', '24999'),
 ('Massachusetts', '25999'),
 ('Michigan', '26999'),
 ('Minnesota', '27999'),
 ('Mississippi', '28999'),
 ('Alaska', '2999'),
 ('Missouri', '29999'),
 ('Montana', '30999'),
 ('Nebraska', '31999'),
 ('Nevada', '32999'),
 ('New Hampshire', '33999'),
 ('New Jersey', '34999'),
 ('New Mexico', '35999'),
 ('New York', '36999'),
 ('North Carolina', '37999'),
 ('North Dakota', '38999'),
 ('Ohio', '39999'),
 ('Oklahoma', '40999'),
 ('Oregon', '41999'),
 ('Pennsylvania', '42999'),
 ('Rhode Island', '44999'),
 ('South Carolina', '45999'),
 ('South Dakota', '46999'),
 ('Tennessee', '47999'),
 ('Texas', '48999'),
 ('Arizona', '4999'),
 ('Utah', '49999

{'Alabama': '1999', 'Alaska': '2999', 'Arizona': '4999', 'Arkansas': '5999', 'California': '6999', 'Colorado': '8999', 'Connecticut': '9999', 'Delaware': '10999', 'Florida': '12999', 'Georgia': '13999', 'Hawaii': '15999', 'Idaho': '16999', 'Illinois': '17999', 'Indiana': '18999', 'Iowa': '19999', 'Kansas': '20999', 'Kentucky': '21999', 'Louisiana': '22999', 'Maine': '23999', 'Maryland': '24999', 'Massachusetts': '25999', 'Michigan': '26999', 'Minnesota': '27999', 'Mississippi': '28999', 'Missouri': '29999', 'Montana': '30999', 'Nebraska': '31999', 'Nevada': '32999', 'New Hampshire': '33999', 'New Jersey': '34999', 'New Mexico': '35999', 'New York': '36999', 'North Carolina': '37999', 'North Dakota': '38999', 'Ohio': '39999', 'Oklahoma': '40999', 'Oregon': '41999', 'Pennsylvania': '42999', 'Rhode Island': '44999', 'South Carolina': '45999', 'South Dakota': '46999', 'Tennessee': '47999', 'Texas': '48999', 'Utah': '49999', 'Vermont': '50999', 'Virginia': '51999', 'Washington': '53999', 'W

### Get county Census data (by FIPS code)

The file [PopulationEstimates.xls](https://www.ers.usda.gov/webdocs/DataFiles/48747/PopulationEstimates.xls?v=5425) is from the [USDA Economic Research Service](https://www.ers.usda.gov/data-products/county-level-data-sets/download-data/). This has more data than the file [co-est2019-annres.xlsx](https://www2.census.gov/programs-surveys/popest/tables/2010-2019/counties/totals/co-est2019-annres.xlsx) directly from the [US Census Bureau](https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html).

Differences:

* ERS data includes data for Puerto Rico (80 more lines)
* ERSS data includes total counts for each state and PR (51 more lines)
* ERS data includes births, deaths, and counts for natural increases, international migration, domestic migration, net migration, etc. (many multiples of the number of columns)

Rural-urban continuum codes are found in ruralurbancodes2013.xls and pr2003.xls (for Puerto Rico), available from [USDA's ERS](https://www.ers.usda.gov/data-products/rural-urban-continuum-codes/). The short summary:

> The 2013 Rural-Urban Continuum Codes form a classification scheme that distinguishes metropolitan counties by the population size of their metro area, and nonmetropolitan counties by degree of urbanization and adjacency to a metro area. The official Office of Management and Budget (OMB) metro and nonmetro categories have been subdivided into three metro and six nonmetro categories. Each county in the U.S. is assigned one of the 9 codes. This scheme allows researchers to break county data into finer residential groups, beyond metro and nonmetro, particularly for the analysis of trends in nonmetro areas that are related to population density and metro influence. The Rural-Urban Continuum Codes were originally developed in 1974. They have been updated each decennial since (1983, 1993, 2003, 2013), and slightly revised in 1988. Note that the 2013 Rural-Urban Continuum Codes are not directly comparable with the codes prior to 2000 because of the new methodology used in developing the 2000 metropolitan areas. See the Documentation for details and a map of the codes.

Information on urban influence codes are found in UrbanInfluenceCodes2013.xls and pr2003UrbInf.xls (for Puerto Rico), available from [USDA's ERS](https://www.ers.usda.gov/data-products/urban-influence-codes/). The short summary:

> The 2013 Urban Influence Codes form a classification scheme that distinguishes metropolitan counties by population size of their metro area, and nonmetropolitan counties by size of the largest city or town and proximity to metro and micropolitan areas. The standard Office of Management and Budget (OMB) metro and nonmetro categories have been subdivided into two metro and 10 nonmetro categories, resulting in a 12-part county classification. This scheme was originally developed in 1993. This scheme allows researchers to break county data into finer residential groups, beyond metro and nonmetro, particularly for the analysis of trends in nonmetro areas that are related to population density and metro influence. 

Information on county economic type codes are found in ERSCountyTypology2015Edition.xls, available from [USDA's ERS](https://www.ers.usda.gov/data-products/county-typology-codes/). The short summary:

> An area's economic and social characteristics have significant effects on its development and need for various types of public programs. To provide policy-relevant information about diverse county conditions to policymakers, public officials, and researchers, ERS has developed a set of county-level typology codes that captures a range of economic and social characteristics.

> The 2015 County Typology Codes classify all U.S. counties according to six mutually exclusive categories of economic dependence and six overlapping categories of policy-relevant themes. The economic dependence types include farming, mining, manufacturing, Federal/State government, recreation, and nonspecialized counties. The policy-relevant types include low education, low employment, persistent poverty, persistent child poverty, population loss, and retirement destination.

(Used in [Create per thousand case values](#Create-per-thousand-case-values).)

In [21]:
dfCensus = pd.read_excel(commonDataPath / 'PopulationEstimates.xls',
                    sheet_name='Population Estimates 2010-19',
                    header=2)
keepColumns = ['FIPStxt', 'State', 'Area_Name', 'Rural-urban_Continuum Code_2013',
               'Urban_Influence_Code_2013', 'Economic_typology_2015',
               'POP_ESTIMATE_2019', 'N_POP_CHG_2019', 'Births_2019', 'Deaths_2019']
dfCensus = dfCensus[keepColumns]
dfCensus.head(8)

FIPStxt State       Area_Name  Rural-urban_Continuum Code_2013  \
0        0    US   United States                              NaN   
1     1000    AL         Alabama                              NaN   
2     1001    AL  Autauga County                              2.0   
3     1003    AL  Baldwin County                              3.0   
4     1005    AL  Barbour County                              6.0   
5     1007    AL     Bibb County                              1.0   
6     1009    AL   Blount County                              1.0   
7     1011    AL  Bullock County                              6.0   

   Urban_Influence_Code_2013  Economic_typology_2015  POP_ESTIMATE_2019  \
0                        NaN                     NaN          328239523   
1                        NaN                     NaN            4903185   
2                        2.0                     0.0              55869   
3                        2.0                     5.0             223234   
4                        6.0                     3.0              24686   
5                        1.0                     0.0              22394   
6                        1.0                     0.0              57826   
7                        6.0                     3.0              10101   

   N_POP_CHG_2019  Births_2019  Deaths_2019  
0       1552022.0    3791712.0    2835038.0  
1         15504.0      57313.0      53879.0  
2           336.0        624.0        541.0  
3          5379.0       2304.0       2326.0  
4          -186.0        256.0        312.0  
5            27.0        240.0        252.0  
6            55.0        651.0        657.0  
7           -73.0        109.0        109.0

### Data Munging

**Beat data into shape**

<font color="darkgreen">**For details with data handling, refer to the [Readme.md](https://github.com/nytimes/covid-19-data) for the *NY Times* data repository. In particular, note:**

* [Methodology and Definitions](https://github.com/nytimes/covid-19-data#methodology-and-definitions)
* [Geographic Exceptions](https://github.com/nytimes/covid-19-data#geographic-exceptions)
</font>

#### Missing fips codes:

An incomplete discussion of this is outlined in [FIPS code for New York City and Rhode Island Missing? #105](https://github.com/nytimes/covid-19-data/issues/105), submitted to issues for the *NY Times* github repo. These are addressed indirectly in the Geographic Exceptions linked above.

##### New York City

* New York City has 5 boroughs, and for each a fips code. However, the *NY Times* has aggregated all of these into 'New York City' county. Set the fips code to 36061, which is correct for Manhattan.
* Later will duplicate values for the other boroughs, represented by FIPS codes 36005, 36047, 36081, and 36085.

In [22]:
df2[(df2.county == 'New York City')]['fips'].head()
df2['fips'] = [36061 if (c == 'New York City') else f \
              for c, f in zip(df2.county, df2.fips)]
df2[(df2.county == 'New York City')]['fips'].head()

416   NaN
448   NaN
482   NaN
518   NaN
565   NaN
Name: fips, dtype: float64

416    36061.0
448    36061.0
482    36061.0
518    36061.0
565    36061.0
Name: fips, dtype: float64

##### Kansas City

From the Geographic Exceptions section of the NY Times repo Readme.md:

> Four counties (Cass, Clay, Jackson and Platte) overlap the municipality of Kansas City, Mo. The cases and deaths that we show for these four counties are only for the portions exclusive of Kansas City. Cases and deaths for Kansas City are reported as their own line.

* For purposes of assigning to a FIPS code, we use 29096, which has not been assigned to any county. (It follows the FIPS code for Jackson County, which contains the largest share of Kansas City.)

In [23]:
df2[(df2.county == 'Kansas City')]['fips'].head()
df2['fips'] = [29096 if (c == 'Kansas City') else f \
              for c, f in zip(df2.county, df2.fips)]
df2[(df2.county == 'Kansas City')]['fips'].head()

5641    NaN
6631    NaN
7720    NaN
8908    NaN
10209   NaN
Name: fips, dtype: float64

5641     29096.0
6631     29096.0
7720     29096.0
8908     29096.0
10209    29096.0
Name: fips, dtype: float64

##### Joplin, MO

> Starting June 25, cases and deaths for Joplin are reported separately from Jasper and Newton counties. The cases and deaths reported for those counties are only for the portions exclusive of Joplin. Joplin cases and deaths previously appeared in the counts for those counties or as Unknown.

* As Joplin is not a county, there is no county FIPS code. Use 29375, otherwise un-used, instead of its actual code: 29-37592

In [24]:
df2[df2.fips == 29375]

Empty DataFrame
Columns: [date, county, state, fips, cases, deaths, confirmed_cases, confirmed_deaths, probable_cases, probable_deaths]
Index: []

In [25]:
df2[(df2.county == 'Joplin')]['fips'].head()
df2['fips'] = [29375 if (c == 'Joplin') else f \
              for c, f in zip(df2.county, df2.fips)]
df2[(df2.county == 'Joplin')]['fips'].head()

272889   NaN
276033   NaN
279182   NaN
282332   NaN
285479   NaN
Name: fips, dtype: float64

272889    29375.0
276033    29375.0
279182    29375.0
282332    29375.0
285479    29375.0
Name: fips, dtype: float64

##### Unknowns

Most states in the database have cases not assigned to any county.

* Assign to these 'Unknown' counties a FIPS `df2['fips'] = StateFIPS[state]`, where that contains those 999 county codes.
* Oregon, North Carolina and Alabama keep good track of cases, and as of 11 Oct 2020, there were no cases assigned to 'Unknown' county.

*Takes about 15s ...*

In [26]:
states = df2.state.unique()
for state in states:
    print(state)
    fips = stateFIPS[state]
    df2[(df2.county == 'Unknown') & (df2.state == state)]['fips'].head(4)
    df2['fips'] = [fips if ((c == 'Unknown') and (s == state)) else f \
              for c, s, f in zip(df2.county, df2.state, df2.fips)]
    df2[(df2.county == 'Unknown') & (df2.state == state)]['fips'].head(4)
    print("")

Washington


10779   NaN
13953   NaN
15722   NaN
17602   NaN
Name: fips, dtype: float64

10779    53999
13953    53999
15722    53999
17602    53999
Name: fips, dtype: object


Illinois


8564     NaN
9828     NaN
11221    NaN
16252    NaN
Name: fips, dtype: object

8564     17999
9828     17999
11221    17999
16252    17999
Name: fips, dtype: object


California


7215     NaN
8358     NaN
24067    NaN
26296    NaN
Name: fips, dtype: object

7215     6999
8358     6999
24067    6999
26296    6999
Name: fips, dtype: object


Arizona


9521     NaN
10891    NaN
12432    NaN
14095    NaN
Name: fips, dtype: object

9521     4999
10891    4999
12432    4999
14095    4999
Name: fips, dtype: object


Massachusetts


2950    NaN
3451    NaN
4034    NaN
4739    NaN
Name: fips, dtype: object

2950    25999
3451    25999
4034    25999
4739    25999
Name: fips, dtype: object


Wisconsin


227684    NaN
230789    NaN
233896    NaN
237004    NaN
Name: fips, dtype: object

227684    55999
230789    55999
233896    55999
237004    55999
Name: fips, dtype: object


Texas


10678    NaN
Name: fips, dtype: object

10678    48999
Name: fips, dtype: object


Nebraska


20800    NaN
25114    NaN
27374    NaN
55254    NaN
Name: fips, dtype: object

20800    31999
25114    31999
27374    31999
55254    31999
Name: fips, dtype: object


Utah


12202    NaN
13838    NaN
15604    NaN
17478    NaN
Name: fips, dtype: object

12202    49999
13838    49999
15604    49999
17478    49999
Name: fips, dtype: object


Oregon


Series([], Name: fips, dtype: object)

Series([], Name: fips, dtype: object)


Florida


7304     NaN
8450     NaN
9695     NaN
11070    NaN
Name: fips, dtype: object

7304     12999
8450     12999
9695     12999
11070    12999
Name: fips, dtype: object


New York


18873    NaN
20912    NaN
23036    NaN
25230    NaN
Name: fips, dtype: object

18873    36999
20912    36999
23036    36999
25230    36999
Name: fips, dtype: object


Rhode Island


418    NaN
450    NaN
485    NaN
522    NaN
Name: fips, dtype: object

418    44999
450    44999
485    44999
522    44999
Name: fips, dtype: object


Georgia


5385    NaN
6319    NaN
7367    NaN
8520    NaN
Name: fips, dtype: object

5385    13999
6319    13999
7367    13999
8520    13999
Name: fips, dtype: object


New Hampshire


32102    NaN
34533    NaN
37003    NaN
39518    NaN
Name: fips, dtype: object

32102    33999
34533    33999
37003    33999
39518    33999
Name: fips, dtype: object


North Carolina


Series([], Name: fips, dtype: object)

Series([], Name: fips, dtype: object)


New Jersey


1511    NaN
1804    NaN
2151    NaN
2559    NaN
Name: fips, dtype: object

1511    34999
1804    34999
2151    34999
2559    34999
Name: fips, dtype: object


Colorado


7246     NaN
8392     NaN
9637     NaN
11011    NaN
Name: fips, dtype: object

7246     8999
8392     8999
9637     8999
11011    8999
Name: fips, dtype: object


Maryland


24779    NaN
27031    NaN
60255    NaN
62976    NaN
Name: fips, dtype: object

24779    24999
27031    24999
60255    24999
62976    24999
Name: fips, dtype: object


Nevada


4828    NaN
5670    NaN
6662    NaN
7752    NaN
Name: fips, dtype: object

4828    32999
5670    32999
6662    32999
7752    32999
Name: fips, dtype: object


Tennessee


5038    NaN
5927    NaN
6944    NaN
8074    NaN
Name: fips, dtype: object

5038    47999
5927    47999
6944    47999
8074    47999
Name: fips, dtype: object


Hawaii


8529     NaN
9790     NaN
11175    NaN
12728    NaN
Name: fips, dtype: object

8529     15999
9790     15999
11175    15999
12728    15999
Name: fips, dtype: object


Indiana


24500    NaN
26740    NaN
29051    NaN
31419    NaN
Name: fips, dtype: object

24500    18999
26740    18999
29051    18999
31419    18999
Name: fips, dtype: object


Kentucky


4680    NaN
5494    NaN
6442    NaN
7516    NaN
Name: fips, dtype: object

4680    21999
5494    21999
6442    21999
7516    21999
Name: fips, dtype: object


Minnesota


6570     NaN
7652     NaN
8832     NaN
10127    NaN
Name: fips, dtype: object

6570     27999
7652     27999
8832     27999
10127    27999
Name: fips, dtype: object


Oklahoma


25456     NaN
289259    NaN
340061    NaN
375322    NaN
Name: fips, dtype: object

25456     40999
289259    40999
340061    40999
375322    40999
Name: fips, dtype: object


Pennsylvania


23341    NaN
30146    NaN
Name: fips, dtype: object

23341    42999
30146    42999
Name: fips, dtype: object


South Carolina


407729    NaN
420610    NaN
430281    NaN
Name: fips, dtype: object

407729    45999
420610    45999
430281    45999
Name: fips, dtype: object


District of Columbia


Series([], Name: fips, dtype: object)

Series([], Name: fips, dtype: object)


Kansas


41472    NaN
46655    NaN
49292    NaN
51958    NaN
Name: fips, dtype: object

41472    20999
46655    20999
49292    20999
51958    20999
Name: fips, dtype: object


Missouri


5647    NaN
6637    NaN
7726    NaN
8919    NaN
Name: fips, dtype: object

5647    29999
6637    29999
7726    29999
8919    29999
Name: fips, dtype: object


Vermont


9358     NaN
10704    NaN
12216    NaN
13852    NaN
Name: fips, dtype: object

9358     50999
10704    50999
12216    50999
13852    50999
Name: fips, dtype: object


Virginia


10748    NaN
12270    NaN
13918    NaN
25962    NaN
Name: fips, dtype: object

10748    51999
12270    51999
13918    51999
25962    51999
Name: fips, dtype: object


Connecticut


19893    NaN
21970    NaN
24129    NaN
26359    NaN
Name: fips, dtype: object

19893    9999
21970    9999
24129    9999
26359    9999
Name: fips, dtype: object


Iowa


24563    NaN
65427    NaN
68176    NaN
76488    NaN
Name: fips, dtype: object

24563    19999
65427    19999
68176    19999
76488    19999
Name: fips, dtype: object


Louisiana


4003    NaN
4703    NaN
5521    NaN
6476    NaN
Name: fips, dtype: object

4003    22999
4703    22999
5521    22999
6476    22999
Name: fips, dtype: object


Ohio


192725    NaN
257775    NaN
295490    NaN
346381    NaN
Name: fips, dtype: object

192725    39999
257775    39999
295490    39999
346381    39999
Name: fips, dtype: object


Michigan


10096    NaN
11512    NaN
13100    NaN
14812    NaN
Name: fips, dtype: object

10096    26999
11512    26999
13100    26999
14812    26999
Name: fips, dtype: object


South Dakota


37538     NaN
40061     NaN
42622     NaN
469074    NaN
Name: fips, dtype: object

37538     46999
40061     46999
42622     46999
469074    46999
Name: fips, dtype: object


Arkansas


5223    NaN
6142    NaN
7176    NaN
8319    NaN
Name: fips, dtype: object

5223    5999
6142    5999
7176    5999
8319    5999
Name: fips, dtype: object


Delaware


46082    NaN
48712    NaN
54053    NaN
56745    NaN
Name: fips, dtype: object

46082    10999
48712    10999
54053    10999
56745    10999
Name: fips, dtype: object


Mississippi


14919     NaN
16743     NaN
250935    NaN
254051    NaN
Name: fips, dtype: object

14919     28999
16743     28999
250935    28999
254051    28999
Name: fips, dtype: object


New Mexico


29760     NaN
94132     NaN
96968     NaN
108397    NaN
Name: fips, dtype: object

29760     35999
94132     35999
96968     35999
108397    35999
Name: fips, dtype: object


North Dakota


47493     NaN
183458    NaN
186515    NaN
189575    NaN
Name: fips, dtype: object

47493     38999
183458    38999
186515    38999
189575    38999
Name: fips, dtype: object


Wyoming


43197    NaN
45795    NaN
56455    NaN
59163    NaN
Name: fips, dtype: object

43197    56999
45795    56999
56455    56999
59163    56999
Name: fips, dtype: object


Alaska


26170     NaN
40700     NaN
160353    NaN
163381    NaN
Name: fips, dtype: object

26170     2999
40700     2999
160353    2999
163381    2999
Name: fips, dtype: object


Maine


2929    NaN
3429    NaN
4011    NaN
4713    NaN
Name: fips, dtype: object

2929    23999
3429    23999
4011    23999
4713    23999
Name: fips, dtype: object


Alabama


Series([], Name: fips, dtype: object)

Series([], Name: fips, dtype: object)


Idaho


12745     NaN
256301    NaN
281397    NaN
573935    NaN
Name: fips, dtype: object

12745     16999
256301    16999
281397    16999
573935    16999
Name: fips, dtype: object


Montana


22902    NaN
25091    NaN
Name: fips, dtype: object

22902    30999
25091    30999
Name: fips, dtype: object


Puerto Rico


1858    NaN
2220    NaN
2642    NaN
3107    NaN
Name: fips, dtype: object

1858    72999
2220    72999
2642    72999
3107    72999
Name: fips, dtype: object


Virgin Islands


2267    NaN
2694    NaN
3166    NaN
3702    NaN
Name: fips, dtype: object

2267    78999
2694    78999
3166    78999
3702    78999
Name: fips, dtype: object


Guam


2422    NaN
2863    NaN
3350    NaN
3912    NaN
Name: fips, dtype: object

2422    66999
2863    66999
3350    66999
3912    66999
Name: fips, dtype: object


West Virginia


26030     NaN
154134    NaN
Name: fips, dtype: object

26030     54999
154134    54999
Name: fips, dtype: object


Northern Mariana Islands


17033    NaN
18967    NaN
21010    NaN
23142    NaN
Name: fips, dtype: object

17033    69999
18967    69999
21010    69999
23142    69999
Name: fips, dtype: object

**Verify that all null fips values are gone**

In [27]:
dfnulls = df2[df2.fips.isnull()]
dfnulls.head()
del dfnulls

Empty DataFrame
Columns: [date, county, state, fips, cases, deaths, confirmed_cases, confirmed_deaths, probable_cases, probable_deaths]
Index: []

#### Convert FIPS codes from float type to 5-character strings

In [28]:
df2[df2.state == 'Alabama'].head(3)
df2['fips'] = [str(int(x)).zfill(5) for x in df2['fips']]
df2.loc[1619:1621, :]

date     county    state  fips  cases  deaths  confirmed_cases  \
1619 2020-03-13     Elmore  Alabama  1051      1     0.0              NaN   
1620 2020-03-13  Jefferson  Alabama  1073      2     0.0              NaN   
1621 2020-03-13  Limestone  Alabama  1083      1     0.0              NaN   

      confirmed_deaths  probable_cases  probable_deaths  
1619               NaN             NaN              NaN  
1620               NaN             NaN              NaN  
1621               NaN             NaN              NaN

date     county    state   fips  cases  deaths  confirmed_cases  \
1619 2020-03-13     Elmore  Alabama  01051      1     0.0              NaN   
1620 2020-03-13  Jefferson  Alabama  01073      2     0.0              NaN   
1621 2020-03-13  Limestone  Alabama  01083      1     0.0              NaN   

      confirmed_deaths  probable_cases  probable_deaths  
1619               NaN             NaN              NaN  
1620               NaN             NaN              NaN  
1621               NaN             NaN              NaN

In [29]:
# df2bak = deepcopy(df2)
# df2 = deepcopy(df2bak)

#### Replace 'Unknown' counties with StateCode-Unknown values

(`StateCode` is created above in [Create a State ⟶ StateCode dict](#Create-a-State-%E2%9F%B6-StateCode-dict))

In [30]:
df2[df2.county == 'Unknown'].tail(3)
df2['county'] = [State2StateCode[s] + '-Unknown' if c == 'Unknown' else c
                for s, c in zip(df2.state, df2.county)]
df2[df2.county.str.contains('-Unknown')].tail(3)

date   county       state   fips  cases  deaths  confirmed_cases  \
673531 2020-10-27  Unknown        Utah  49999     87     1.0             35.0   
673548 2020-10-27  Unknown     Vermont  50999      8     0.0              8.0   
673722 2020-10-27  Unknown  Washington  53999      2     2.0              0.0   

        confirmed_deaths  probable_cases  probable_deaths  
673531               1.0            52.0              0.0  
673548               0.0             NaN              NaN  
673722               0.0             2.0              2.0

date      county       state   fips  cases  deaths  \
673531 2020-10-27  UT-Unknown        Utah  49999     87     1.0   
673548 2020-10-27  VT-Unknown     Vermont  50999      8     0.0   
673722 2020-10-27  WA-Unknown  Washington  53999      2     2.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
673531             35.0               1.0            52.0              0.0  
673548              8.0               0.0             NaN              NaN  
673722              0.0               0.0             2.0              2.0

#### Create duplicate values for Manhattan for each of 4 other boroughs

* Duplicate values for New York City, FIPS 36061, for the other four boroughs having FIPS values of 36005, 36047, 36081, and 36085
* Want all 5 boroughs to match Manhattan, so that the whole city will show up in choropleths with the same values.

In [31]:
dfNYC = df2[df2.fips == '36061'].copy()
dfNYC['fips'] = '36005'
df2 = pd.concat([df2, dfNYC])
dfNYC['fips'] = '36047'
df2 = pd.concat([df2, dfNYC])
dfNYC['fips'] = '36081'
df2 = pd.concat([df2, dfNYC])
dfNYC['fips'] = '36085'
df2 = pd.concat([df2, dfNYC]).reset_index(drop=True)
df2[df2.fips == '36005'].head(3)
df2[df2.fips == '36047'].head(3)
df2[df2.fips == '36081'].head(3)
df2[df2.fips == '36085'].head(3)

date         county     state   fips  cases  deaths  \
673878 2020-03-01  New York City  New York  36005      1     0.0   
673879 2020-03-02  New York City  New York  36005      1     0.0   
673880 2020-03-03  New York City  New York  36005      2     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
673878              NaN               NaN             NaN              NaN  
673879              NaN               NaN             NaN              NaN  
673880              NaN               NaN             NaN              NaN

date         county     state   fips  cases  deaths  \
674119 2020-03-01  New York City  New York  36047      1     0.0   
674120 2020-03-02  New York City  New York  36047      1     0.0   
674121 2020-03-03  New York City  New York  36047      2     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
674119              NaN               NaN             NaN              NaN  
674120              NaN               NaN             NaN              NaN  
674121              NaN               NaN             NaN              NaN

date         county     state   fips  cases  deaths  \
674360 2020-03-01  New York City  New York  36081      1     0.0   
674361 2020-03-02  New York City  New York  36081      1     0.0   
674362 2020-03-03  New York City  New York  36081      2     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
674360              NaN               NaN             NaN              NaN  
674361              NaN               NaN             NaN              NaN  
674362              NaN               NaN             NaN              NaN

date         county     state   fips  cases  deaths  \
674601 2020-03-01  New York City  New York  36085      1     0.0   
674602 2020-03-02  New York City  New York  36085      1     0.0   
674603 2020-03-03  New York City  New York  36085      2     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
674601              NaN               NaN             NaN              NaN  
674602              NaN               NaN             NaN              NaN  
674603              NaN               NaN             NaN              NaN

#### Create reverse dict, providing county from fips

Rather than using dffc, need to work from fips values in df2, since that DataFrame includes those weird cases, above, for which FIPS codes were manually added.

* Extract a unique set of `['county', 'fips']` labels using `.drop_duplicates()`
* *Note that there is a degeneracy of 5 for NY City FIPS values*

In [32]:
NYCityFIPS = ['36061', '36005', '36047', '36081', '36085']

uniqCountyFIPS = df2[['county', 'fips']].drop_duplicates()
FIPScounty = dict()
for c, f in zip(uniqCountyFIPS.county, uniqCountyFIPS.fips):
    FIPScounty[f] = c

# Print 10 examples
i = 0
for k, v in FIPScounty.items():
    if ('-Unknown' in v) and (i < 10):
        print(k, v)
        i += 1

for k, v in FIPScounty.items():
    if k in NYCityFIPS:
        print(k, v)

44999 RI-Unknown
34999 NJ-Unknown
72999 PR-Unknown
78999 VI-Unknown
66999 GU-Unknown
23999 ME-Unknown
25999 MA-Unknown
22999 LA-Unknown
21999 KY-Unknown
32999 NV-Unknown
36061 New York City
36005 New York City
36047 New York City
36081 New York City
36085 New York City


#### Group by county and aggregate values by week, starting on Mondays

Want to group by fips (county), and then aggregate values by week starting on Mondays, such that for a given Monday the sums are for the week to follow.

* Create a new datetime variable `'weekStart'` to indicate the Monday of the week for each `date`. Described in 
[Get Week Start Date (Monday) from a date column in Python (pandas)?](https://stackoverflow.com/questions/27989120/get-week-start-date-monday-from-a-date-column-in-python-pandas)

In [33]:
quantities = ['cases', 'confirmed_cases', 'confirmed_deaths',
              'deaths', 'probable_cases', 'probable_deaths']
df2['weekStart'] = df2['date'].dt.to_period('W-SUN').apply(lambda r: r.start_time.tz_localize(None))
weekStarts = df2.weekStart.unique()
print(weekStarts)
df2.head()

['2020-01-20T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-13T00:00:00.000000000' '2020-04-20T00:00:00.000000000'
 '2020-04-27T00:00:00.000000000' '2020-05-04T00:00:00.000000000'
 '2020-05-11T00:00:00.000000000' '2020-05-18T00:00:00.000000000'
 '2020-05-25T00:00:00.000000000' '2020-06-01T00:00:00.000000000'
 '2020-06-08T00:00:00.000000000' '2020-06-15T00:00:00.000000000'
 '2020-06-22T00:00:00.000000000' '2020-06-29T00:00:00.000000000'
 '2020-07-06T00:00:00.000000000' '2020-07-13T00:00:00.000000000'
 '2020-07-20T00:00:00.000000000' '2020-07-27T00:00:00.000000000'
 '2020-08-03T00:00:00.000000000' '2020-08-10T00:00:00.000000000'
 '2020-08-17T00:00:00.000

date     county       state   fips  cases  deaths  confirmed_cases  \
0 2020-01-21  Snohomish  Washington  53061      1     0.0              NaN   
1 2020-01-22  Snohomish  Washington  53061      1     0.0              NaN   
2 2020-01-23  Snohomish  Washington  53061      1     0.0              NaN   
3 2020-01-24       Cook    Illinois  17031      1     0.0              NaN   
4 2020-01-24  Snohomish  Washington  53061      1     0.0              NaN   

   confirmed_deaths  probable_cases  probable_deaths  weekStart  
0               NaN             NaN              NaN 2020-01-20  
1               NaN             NaN              NaN 2020-01-20  
2               NaN             NaN              NaN 2020-01-20  
3               NaN             NaN              NaN 2020-01-20  
4               NaN             NaN              NaN 2020-01-20

In [34]:
df2[df2.county.str.contains('Unknown')].head()

date      county         state   fips  cases  deaths  \
418 2020-03-01  RI-Unknown  Rhode Island  44999      2     0.0   
450 2020-03-02  RI-Unknown  Rhode Island  44999      2     0.0   
485 2020-03-03  RI-Unknown  Rhode Island  44999      2     0.0   
522 2020-03-04  RI-Unknown  Rhode Island  44999      2     0.0   
569 2020-03-05  RI-Unknown  Rhode Island  44999      2     0.0   

     confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  \
418              NaN               NaN             NaN              NaN   
450              NaN               NaN             NaN              NaN   
485              NaN               NaN             NaN              NaN   
522              NaN               NaN             NaN              NaN   
569              NaN               NaN             NaN              NaN   

     weekStart  
418 2020-02-24  
450 2020-03-02  
485 2020-03-02  
522 2020-03-02  
569 2020-03-02

* Group by `'fips'` and by new `'weekStart'` variable, having a frequency of one week
* Aggregate using `.max()` to get maximum for the week starting on `weekStart`.
* `.reset_index()` to clean up.
* Create a 'county' variable that contains county name or `<state>-Unknown`.

*Takes about 20s ...*

In [35]:
dfg = df2.groupby(['fips', 'weekStart']).max().sort_values(by=['state', 'county', 'weekStart']).reset_index()
dfg['county'] = dfg['fips'].apply(lambda f: FIPScounty[f])
dfg.tail()

fips  weekStart       date  county    state  cases  deaths  \
100207  56045 2020-09-28 2020-10-04  Weston  Wyoming     42     0.0   
100208  56045 2020-10-05 2020-10-11  Weston  Wyoming     58     0.0   
100209  56045 2020-10-12 2020-10-18  Weston  Wyoming     93     0.0   
100210  56045 2020-10-19 2020-10-25  Weston  Wyoming    127     0.0   
100211  56045 2020-10-26 2020-10-27  Weston  Wyoming    139     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
100207              NaN               NaN             NaN              NaN  
100208              NaN               NaN             NaN              NaN  
100209              NaN               NaN             NaN              NaN  
100210              NaN               NaN             NaN              NaN  
100211            109.0               NaN            30.0              NaN

In [36]:
dftmp = df2[df2.fips == '56045'].sort_values(by=['date']).tail(21)
dftmp[(dftmp.date >= pd.to_datetime('2020-10-05')) & (dftmp.date <= pd.to_datetime('2020-10-11'))]

date  county    state   fips  cases  deaths  confirmed_cases  \
608995 2020-10-07  Weston  Wyoming  56045     50     0.0              NaN   
612237 2020-10-08  Weston  Wyoming  56045     51     0.0              NaN   
615478 2020-10-09  Weston  Wyoming  56045     54     0.0              NaN   
618720 2020-10-10  Weston  Wyoming  56045     58     0.0              NaN   
621963 2020-10-11  Weston  Wyoming  56045     58     0.0              NaN   

        confirmed_deaths  probable_cases  probable_deaths  weekStart  
608995               NaN             NaN              NaN 2020-10-05  
612237               NaN             NaN              NaN 2020-10-05  
615478               NaN             NaN              NaN 2020-10-05  
618720               NaN             NaN              NaN 2020-10-05  
621963               NaN             NaN              NaN 2020-10-05

In [37]:
dfg[dfg.weekStart == pd.to_datetime('2020-10-05')].head()

fips  weekStart       date   county    state  cases  deaths  \
28   01001 2020-10-05 2020-10-11  Autauga  Alabama   1905    28.0   
62   01003 2020-10-05 2020-10-11  Baldwin  Alabama   6203    65.0   
93   01005 2020-10-05 2020-10-11  Barbour  Alabama    942     9.0   
124  01007 2020-10-05 2020-10-11     Bibb  Alabama    736    12.0   
156  01009 2020-10-05 2020-10-11   Blount  Alabama   1713    16.0   

     confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  
28               NaN               NaN             NaN              NaN  
62               NaN               NaN             NaN              NaN  
93               NaN               NaN             NaN              NaN  
124              NaN               NaN             NaN              NaN  
156              NaN               NaN             NaN              NaN

In [38]:
dftmp = df2[df2.fips == '01001'].sort_values(by=['date']).tail(9)
dftmp[(dftmp.date >= pd.to_datetime('2020-10-19')) & (dftmp.date <= pd.to_datetime('2020-10-25'))]

date   county    state   fips  cases  deaths  confirmed_cases  \
644679 2020-10-19  Autauga  Alabama  01001   1999    28.0              NaN   
647924 2020-10-20  Autauga  Alabama  01001   2010    29.0              NaN   
651168 2020-10-21  Autauga  Alabama  01001   2021    30.0              NaN   
654413 2020-10-22  Autauga  Alabama  01001   2023    30.0              NaN   
657658 2020-10-23  Autauga  Alabama  01001   2030    30.0              NaN   
660902 2020-10-24  Autauga  Alabama  01001   2048    31.0              NaN   
664147 2020-10-25  Autauga  Alabama  01001   2059    31.0              NaN   

        confirmed_deaths  probable_cases  probable_deaths  weekStart  
644679               NaN             NaN              NaN 2020-10-19  
647924               NaN             NaN              NaN 2020-10-19  
651168               NaN             NaN              NaN 2020-10-19  
654413               NaN             NaN              NaN 2020-10-19  
657658               NaN             NaN              NaN 2020-10-19  
660902               NaN             NaN              NaN 2020-10-19  
664147               NaN             NaN              NaN 2020-10-19

### Difference totals to get new cases/deaths

In [39]:
dfg['new_cases'] = dfg.groupby(['fips'])['cases'].diff().fillna(0)
dfg['new_deaths'] = dfg.groupby(['fips'])['deaths'].diff().fillna(0)
dfg.tail()

fips  weekStart       date  county    state  cases  deaths  \
100207  56045 2020-09-28 2020-10-04  Weston  Wyoming     42     0.0   
100208  56045 2020-10-05 2020-10-11  Weston  Wyoming     58     0.0   
100209  56045 2020-10-12 2020-10-18  Weston  Wyoming     93     0.0   
100210  56045 2020-10-19 2020-10-25  Weston  Wyoming    127     0.0   
100211  56045 2020-10-26 2020-10-27  Weston  Wyoming    139     0.0   

        confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  \
100207              NaN               NaN             NaN              NaN   
100208              NaN               NaN             NaN              NaN   
100209              NaN               NaN             NaN              NaN   
100210              NaN               NaN             NaN              NaN   
100211            109.0               NaN            30.0              NaN   

        new_cases  new_deaths  
100207        6.0         0.0  
100208       16.0         0.0  
100209       35.0         0.0  
100210       34.0         0.0  
100211       12.0         0.0

### Create per thousand case values

`dfCensus` was imported in [Get county Census data (by FIPS code)](#Get-county-Census-data-(by-FIPS-code))

* start by creating a modified version, `dfc`, of the census DataFrame `dfCensus`.
  * cast FIPtxt astype(str)
  * aggregate the population values for the 5 NY City boroughs
  * duplicate the aggregate values for each of the 5 boroughs, so all boroughs will have those totals
  * **<font color="darkred">do we need to add Kansas City values to Jackson County?</font>**
* LEFT JOIN dfg with dfc to get population values for each FIPS value
* create new columns in dfg to get per capita cases, confirmed cases, deaths, confirmed deaths, probable cases, probable deaths

#### Set all NY City populations to total

In [40]:
dfc = dfCensus[['FIPStxt', 'State', 'Area_Name', 'POP_ESTIMATE_2019']].copy()
dfc['FIPStxt'] = [str(int(x)).zfill(5) for x in dfc['FIPStxt']]
NYCpop = dfc[dfc.FIPStxt.isin(NYCityFIPS)]['POP_ESTIMATE_2019'].sum()
dfc[dfc.FIPStxt.isin(NYCityFIPS)]
dfc['POP_ESTIMATE_2019'] = [NYCpop if f in NYCityFIPS else p
                                  for f, p in zip(dfc.FIPStxt, dfc.POP_ESTIMATE_2019)]
dfc[dfc.FIPStxt.isin(NYCityFIPS)]

FIPStxt State        Area_Name  POP_ESTIMATE_2019
1864   36005    NY     Bronx County            1418207
1885   36047    NY     Kings County            2559903
1892   36061    NY  New York County            1628706
1902   36081    NY    Queens County            2253858
1904   36085    NY  Richmond County             476143

FIPStxt State        Area_Name  POP_ESTIMATE_2019
1864   36005    NY     Bronx County            8336817
1885   36047    NY     Kings County            8336817
1892   36061    NY  New York County            8336817
1902   36081    NY    Queens County            8336817
1904   36085    NY  Richmond County            8336817

#### Join dfC with dfg to add populations

In [41]:
df = pd.merge(dfg, dfc[['FIPStxt', 'POP_ESTIMATE_2019']], how='left', left_on='fips', right_on='FIPStxt')
del df['FIPStxt']
df = df.sort_values(by=['weekStart', 'fips']).reset_index(drop=True)
df['weekStr'] = df.weekStart.apply(lambda x: x.strftime('%Y-%m-%d'))

df.head(4)
df.tail(4)

fips  weekStart       date       county       state  cases  deaths  \
0  04013 2020-01-20 2020-01-26     Maricopa     Arizona      1     0.0   
1  06037 2020-01-20 2020-01-26  Los Angeles  California      1     0.0   
2  06059 2020-01-20 2020-01-26       Orange  California      1     0.0   
3  17031 2020-01-20 2020-01-26         Cook    Illinois      1     0.0   

   confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  \
0              NaN               NaN             NaN              NaN   
1              NaN               NaN             NaN              NaN   
2              NaN               NaN             NaN              NaN   
3              NaN               NaN             NaN              NaN   

   new_cases  new_deaths  POP_ESTIMATE_2019     weekStr  
0        0.0         0.0          4485414.0  2020-01-20  
1        0.0         0.0         10039107.0  2020-01-20  
2        0.0         0.0          3175692.0  2020-01-20  
3        0.0         0.0          5150233.0  2020-01-20

fips  weekStart       date      county           state  cases  \
100208  72999 2020-10-26 2020-10-27  PR-Unknown     Puerto Rico   1945   
100209  78010 2020-10-26 2020-10-27   St. Croix  Virgin Islands    504   
100210  78020 2020-10-26 2020-10-27    St. John  Virgin Islands     67   
100211  78030 2020-10-26 2020-10-27  St. Thomas  Virgin Islands    780   

        deaths  confirmed_cases  confirmed_deaths  probable_cases  \
100208     0.0            770.0               NaN          1175.0   
100209     6.0            504.0               6.0             NaN   
100210     1.0             67.0               1.0             NaN   
100211    14.0            780.0              14.0             NaN   

        probable_deaths  new_cases  new_deaths  POP_ESTIMATE_2019     weekStr  
100208              NaN       42.0         0.0                NaN  2020-10-26  
100209              NaN        2.0         0.0                NaN  2020-10-26  
100210              NaN        0.0         0.0                NaN  2020-10-26  
100211              NaN        3.0         0.0                NaN  2020-10-26

#### Create the variables

In [42]:
df['casesk'] = 1000.0*df.cases / df.POP_ESTIMATE_2019
df['deathsk'] = 1000.0*df.deaths / df.POP_ESTIMATE_2019
df['casesConfk'] = 1000.0*df.confirmed_cases / df.POP_ESTIMATE_2019
df['deathsConfk'] = 1000.0*df.confirmed_deaths / df.POP_ESTIMATE_2019
df['casesProbk'] = 1000.0*df.probable_cases / df.POP_ESTIMATE_2019
df['deathsProbk'] = 1000.0*df.probable_deaths / df.POP_ESTIMATE_2019
df['log10cases'] = np.log10(df.cases)
df['log10deaths'] = np.log10(df.deaths)
df['log10casesk'] = np.log10(df.casesk)
df['log10deathsk'] = np.log10(df.deathsk)
df['newcasesK'] = 1000.0*df.new_cases / df.POP_ESTIMATE_2019
df['newdeathsK'] = 1000.0*df.new_deaths / df.POP_ESTIMATE_2019
df.head().T

/usr/local/lib/python3.6/dist-packages/pandas/core/series.py:726: RuntimeWarning:

divide by zero encountered in log10



0                    1  \
fips                             04013                06037   
weekStart          2020-01-20 00:00:00  2020-01-20 00:00:00   
date               2020-01-26 00:00:00  2020-01-26 00:00:00   
county                        Maricopa          Los Angeles   
state                          Arizona           California   
cases                                1                    1   
deaths                               0                    0   
confirmed_cases                    NaN                  NaN   
confirmed_deaths                   NaN                  NaN   
probable_cases                     NaN                  NaN   
probable_deaths                    NaN                  NaN   
new_cases                            0                    0   
new_deaths                           0                    0   
POP_ESTIMATE_2019          4.48541e+06          1.00391e+07   
weekStr                     2020-01-20           2020-01-20   
casesk                     0.000222945          9.96105e-05   
deathsk                              0                    0   
casesConfk                         NaN                  NaN   
deathsConfk                        NaN                  NaN   
casesProbk                         NaN                  NaN   
deathsProbk                        NaN                  NaN   
log10cases                           0                    0   
log10deaths                       -inf                 -inf   
log10casesk                    -3.6518              -4.0017   
log10deathsk                      -inf                 -inf   
newcasesK                            0                    0   
newdeathsK                           0                    0   

                                     2                    3  \
fips                             06059                17031   
weekStart          2020-01-20 00:00:00  2020-01-20 00:00:00   
date               2020-01-26 00:00:00  2020-01-26 00:00:00   
county                          Orange                 Cook   
state                       California             Illinois   
cases                                1                    1   
deaths                               0                    0   
confirmed_cases                    NaN                  NaN   
confirmed_deaths                   NaN                  NaN   
probable_cases                     NaN                  NaN   
probable_deaths                    NaN                  NaN   
new_cases                            0                    0   
new_deaths                           0                    0   
POP_ESTIMATE_2019          3.17569e+06          5.15023e+06   
weekStr                     2020-01-20           2020-01-20   
casesk                     0.000314892          0.000194166   
deathsk                              0                    0   
casesConfk                         NaN                  NaN   
deathsConfk                        NaN                  NaN   
casesProbk                         NaN                  NaN   
deathsProbk                        NaN                  NaN   
log10cases                           0                    0   
log10deaths                       -inf                 -inf   
log10casesk                   -3.50184             -3.71183   
log10deathsk                      -inf                 -inf   
newcasesK                            0                    0   
newdeathsK                           0                    0   

                                     4  
fips                             53061  
weekStart          2020-01-20 00:00:00  
date               2020-01-26 00:00:00  
county                       Snohomish  
state                       Washington  
cases                                1  
deaths                               0  
confirmed_cases                    NaN  
confirmed_deaths                   NaN  
probable_cases                     NaN  
probable_deaths                    NaN  
new_cases      

### Save `df`

* Currently using feather format

In [43]:
df.to_feather(dataPath / 'MungedCovid19v1.2.ftr')

#### Testing reliability of reading in saved df

In [48]:
df = pd.read_feather(dataPath / 'MungedCovid19v1.2.ftr')

## National aggregates

* want death counts lagged by 3 weeks, since that is the approximate interval by which deaths lag case identifications
* before creating death counts lagged by 3 weeks, need to reindex to fill in all missing dates for each FIPS code


* since counts for all NY City boroughs were equated to the total, there is massive duplication
* need to remove FIPS codes 36005, 36047, 36081, and 36085 prior to aggregating national totals

In [49]:
df['fips'] = df.fips.astype(int)
df[['weekStr', 'fips', 'cases', 'deaths']].head(8)
df[['weekStr', 'fips', 'cases', 'deaths']].tail(8)
df.info()

weekStr   fips  cases  deaths
0  2020-01-20   4013      1     0.0
1  2020-01-20   6037      1     0.0
2  2020-01-20   6059      1     0.0
3  2020-01-20  17031      1     0.0
4  2020-01-20  53061      1     0.0
5  2020-01-27   4013      1     0.0
6  2020-01-27   6037      1     0.0
7  2020-01-27   6059      1     0.0

weekStr   fips  cases  deaths
100204  2020-10-26  72147    104     0.0
100205  2020-10-26  72149    229     0.0
100206  2020-10-26  72151    473     0.0
100207  2020-10-26  72153    559     0.0
100208  2020-10-26  72999   1945     0.0
100209  2020-10-26  78010    504     6.0
100210  2020-10-26  78020     67     1.0
100211  2020-10-26  78030    780    14.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100212 entries, 0 to 100211
Data columns (total 27 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   fips               100212 non-null  int64         
 1   weekStart          100212 non-null  datetime64[ns]
 2   date               100212 non-null  datetime64[ns]
 3   county             100212 non-null  object        
 4   state              100212 non-null  object        
 5   cases              100212 non-null  int64         
 6   deaths             100212 non-null  float64       
 7   confirmed_cases    2498 non-null    float64       
 8   confirmed_deaths   2031 non-null    float64       
 9   probable_cases     1473 non-null    float64       
 10  probable_deaths    844 non-null     float64       
 11  new_cases          100212 non-null  float64       
 12  new_deaths         100212 non-null  float64       
 13  POP_ESTIMATE_2019  99064 non-null   float64 

### Add rows for all weeks, all fips values

In [50]:
date0 = df.weekStart.min()
date1 = df.weekStart.max()
print(date0, date1)
dates = pd.date_range(start=date0, end=date1, freq='W-MON')
dates = dates.tz_localize(None)
print(weekStarts)
print(dates)

df = df.sort_values(['fips', 'weekStart'])
df.head()
df = df.set_index('weekStart')
df.head()
dfg = df.groupby('fips')
for i, (fips, dfgroup) in enumerate(dfg):
    if i % 100 == 0:
        print(".", end="")

    county = dfgroup.loc[dfgroup.index[0], 'county']
    state = dfgroup.loc[dfgroup.index[0], 'state']
    POP_ESTIMATE_2019 = dfgroup.loc[dfgroup.index[0], 'POP_ESTIMATE_2019']

    if fips == 53033:
        print("\ndfgroup.head()")
        dfgroup.head()
        print("dfgroup.tail()")
        dfgroup.tail()
    bigGroup = pd.DataFrame(dfgroup).reindex(dates)
    if fips == 53033:
        print("\nbigGroup.tail()")
        bigGroup.tail()
    bigGroup['county'] = county
    bigGroup['state'] = state
    bigGroup['POP_ESTIMATE_2019'] = POP_ESTIMATE_2019

    if i == 0:
        dfall = bigGroup
    else:
        dfall = pd.concat([dfall, bigGroup])
        del bigGroup
        if fips == 53033:
            print("dfall.tail()")
            dfall.tail()
            print("")

2020-01-20 00:00:00 2020-10-26 00:00:00
['2020-01-20T00:00:00.000000000' '2020-01-27T00:00:00.000000000'
 '2020-02-03T00:00:00.000000000' '2020-02-10T00:00:00.000000000'
 '2020-02-17T00:00:00.000000000' '2020-02-24T00:00:00.000000000'
 '2020-03-02T00:00:00.000000000' '2020-03-09T00:00:00.000000000'
 '2020-03-16T00:00:00.000000000' '2020-03-23T00:00:00.000000000'
 '2020-03-30T00:00:00.000000000' '2020-04-06T00:00:00.000000000'
 '2020-04-13T00:00:00.000000000' '2020-04-20T00:00:00.000000000'
 '2020-04-27T00:00:00.000000000' '2020-05-04T00:00:00.000000000'
 '2020-05-11T00:00:00.000000000' '2020-05-18T00:00:00.000000000'
 '2020-05-25T00:00:00.000000000' '2020-06-01T00:00:00.000000000'
 '2020-06-08T00:00:00.000000000' '2020-06-15T00:00:00.000000000'
 '2020-06-22T00:00:00.000000000' '2020-06-29T00:00:00.000000000'
 '2020-07-06T00:00:00.000000000' '2020-07-13T00:00:00.000000000'
 '2020-07-20T00:00:00.000000000' '2020-07-27T00:00:00.000000000'
 '2020-08-03T00:00:00.000000000' '2020-08-10T00:00

fips  weekStart       date   county    state  cases  deaths  \
1770   1001 2020-03-23 2020-03-29  Autauga  Alabama      6     0.0   
3751   1001 2020-03-30 2020-04-05  Autauga  Alabama     12     0.0   
6204   1001 2020-04-06 2020-04-12  Autauga  Alabama     19     1.0   
8894   1001 2020-04-13 2020-04-19  Autauga  Alabama     27     2.0   
11675  1001 2020-04-20 2020-04-26  Autauga  Alabama     37     2.0   

       confirmed_cases  confirmed_deaths  probable_cases  probable_deaths  \
1770               NaN               NaN             NaN              NaN   
3751               NaN               NaN             NaN              NaN   
6204               NaN               NaN             NaN              NaN   
8894               NaN               NaN             NaN              NaN   
11675              NaN               NaN             NaN              NaN   

       new_cases  new_deaths  POP_ESTIMATE_2019     weekStr    casesk  \
1770         0.0         0.0            55869.0  2020-03-23  0.107394   
3751         6.0         0.0            55869.0  2020-03-30  0.214788   
6204         7.0         1.0            55869.0  2020-04-06  0.340081   
8894         8.0         1.0            55869.0  2020-04-13  0.483273   
11675       10.0         0.0            55869.0  2020-04-20  0.662264   

        deathsk  casesConfk  deathsConfk  casesProbk  deathsProbk  log10cases  \
1770   0.000000         NaN          NaN         NaN          NaN    0.778151   
3751   0.000000         NaN          NaN         NaN          NaN    1.079181   
6204   0.017899         NaN          NaN         NaN          NaN    1.278754   
8894   0.035798         NaN          NaN         NaN          NaN    1.431364   
11675  0.035798         NaN          NaN         NaN          NaN    1.568202   

       log10deaths  log10casesk  log10deathsk  newcasesK  newdeathsK  
1770          -inf    -0.969020          -inf   0.000000    0.000000  
3751          -inf    -0.667990          -inf   0.107394    0.000000  
6204       0.00000    -0.468417     -1.747171   0.125293    0.017899  
8894       0.30103    -0.315807     -1.446141   0.143192    0.017899  
11675      0.30103    -0.178969     -1.446141   0.178990    0.000000

fips       date   county    state  cases  deaths  confirmed_cases  \
weekStart                                                                       
2020-03-23  1001 2020-03-29  Autauga  Alabama      6     0.0              NaN   
2020-03-30  1001 2020-04-05  Autauga  Alabama     12     0.0              NaN   
2020-04-06  1001 2020-04-12  Autauga  Alabama     19     1.0              NaN   
2020-04-13  1001 2020-04-19  Autauga  Alabama     27     2.0              NaN   
2020-04-20  1001 2020-04-26  Autauga  Alabama     37     2.0              NaN   

            confirmed_deaths  probable_cases  probable_deaths  new_cases  \
weekStart                                                                  
2020-03-23               NaN             NaN              NaN        0.0   
2020-03-30               NaN             NaN              NaN        6.0   
2020-04-06               NaN             NaN              NaN        7.0   
2020-04-13               NaN             NaN              NaN        8.0   
2020-04-20               NaN             NaN              NaN       10.0   

            new_deaths  POP_ESTIMATE_2019     weekStr    casesk   deathsk  \
weekStart                                                                   
2020-03-23         0.0            55869.0  2020-03-23  0.107394  0.000000   
2020-03-30         0.0            55869.0  2020-03-30  0.214788  0.000000   
2020-04-06         1.0            55869.0  2020-04-06  0.340081  0.017899   
2020-04-13         1.0            55869.0  2020-04-13  0.483273  0.035798   
2020-04-20         0.0            55869.0  2020-04-20  0.662264  0.035798   

            casesConfk  deathsConfk  casesProbk  deathsProbk  log10cases  \
weekStart                                                                  
2020-03-23         NaN          NaN         NaN          NaN    0.778151   
2020-03-30         NaN          NaN         NaN          NaN    1.079181   
2020-04-06         NaN          NaN         NaN          NaN    1.278754   
2020-04-13         NaN          NaN         NaN          NaN    1.431364   
2020-04-20         NaN          NaN         NaN          NaN    1.568202   

            log10deaths  log10casesk  log10deathsk  newcasesK  newdeathsK  
weekStart                                                                  
2020-03-23         -inf    -0.969020          -inf   0.000000    0.000000  
2020-03-30         -inf    -0.667990          -inf   0.107394    0.000000  
2020-04-06      0.00000    -0.468417     -1.747171   0.125293    0.017899  
2020-04-13      0.30103    -0.315807     -1.446141   0.143192    0.017899  
2020-04-20      0.30103    -0.178969     -1.446141   0.178990    0.000000

...............................
dfgroup.head()


fips       date county       state  cases  deaths  \
weekStart                                                        
2020-02-24  53033 2020-03-01   King  Washington     11     3.0   
2020-03-02  53033 2020-03-08   King  Washington     91    18.0   
2020-03-09  53033 2020-03-15   King  Washington    421    38.0   
2020-03-16  53033 2020-03-22   King  Washington   1036    77.0   
2020-03-23  53033 2020-03-29   King  Washington   2163   146.0   

            confirmed_cases  confirmed_deaths  probable_cases  \
weekStart                                                       
2020-02-24              NaN               NaN             NaN   
2020-03-02              NaN               NaN             NaN   
2020-03-09              NaN               NaN             NaN   
2020-03-16              NaN               NaN             NaN   
2020-03-23              NaN               NaN             NaN   

            probable_deaths  new_cases  new_deaths  POP_ESTIMATE_2019  \
weekStart                                                               
2020-02-24              NaN        0.0         0.0          2252782.0   
2020-03-02              NaN       80.0        15.0          2252782.0   
2020-03-09              NaN      330.0        20.0          2252782.0   
2020-03-16              NaN      615.0        39.0          2252782.0   
2020-03-23              NaN     1127.0        69.0          2252782.0   

               weekStr    casesk   deathsk  casesConfk  deathsConfk  \
weekStart                                                             
2020-02-24  2020-02-24  0.004883  0.001332         NaN          NaN   
2020-03-02  2020-03-02  0.040394  0.007990         NaN          NaN   
2020-03-09  2020-03-09  0.186880  0.016868         NaN          NaN   
2020-03-16  2020-03-16  0.459876  0.034180         NaN          NaN   
2020-03-23  2020-03-23  0.960146  0.064809         NaN          NaN   

            casesProbk  deathsProbk  log10cases  log10deaths  log10casesk  \
weekStart                                                                   
2020-02-24         NaN          NaN    1.041393     0.477121    -2.311326   
2020-03-02         NaN          NaN    1.959041     1.255273    -1.393678   
2020-03-09         NaN          NaN    2.624282     1.579784    -0.728437   
2020-03-16         NaN          NaN    3.015360     1.886491    -0.337359   
2020-03-23         NaN          NaN    3.335057     2.164353    -0.017663   

            log10deathsk  newcasesK  newdeathsK  
weekStart                                        
2020-02-24     -2.875598   0.000000    0.000000  
2020-03-02     -2.097447   0.035512    0.006658  
2020-03-09     -1.772936   0.146486    0.008878  
2020-03-16     -1.466228   0.272996    0.017312  
2020-03-23     -1.188366   0.500270    0.030629

dfgroup.tail()


fips       date county       state  cases  deaths  \
weekStart                                                        
2020-09-28  53033 2020-10-04   King  Washington  23042   787.0   
2020-10-05  53033 2020-10-11   King  Washington  24072   803.0   
2020-10-12  53033 2020-10-18   King  Washington  25116   812.0   
2020-10-19  53033 2020-10-25   King  Washington  26360   819.0   
2020-10-26  53033 2020-10-27   King  Washington  26618   828.0   

            confirmed_cases  confirmed_deaths  probable_cases  \
weekStart                                                       
2020-09-28              NaN               NaN             NaN   
2020-10-05              NaN               NaN             NaN   
2020-10-12              NaN               NaN             NaN   
2020-10-19              NaN               NaN             NaN   
2020-10-26          26601.0             811.0            17.0   

            probable_deaths  new_cases  new_deaths  POP_ESTIMATE_2019  \
weekStart                                                               
2020-09-28              NaN      905.0         0.0          2252782.0   
2020-10-05              NaN     1030.0        16.0          2252782.0   
2020-10-12              NaN     1044.0         9.0          2252782.0   
2020-10-19              NaN     1244.0         7.0          2252782.0   
2020-10-26             17.0      258.0         9.0          2252782.0   

               weekStr     casesk   deathsk  casesConfk  deathsConfk  \
weekStart                                                              
2020-09-28  2020-09-28  10.228242  0.349346         NaN          NaN   
2020-10-05  2020-10-05  10.685455  0.356448         NaN          NaN   
2020-10-12  2020-10-12  11.148882  0.360443         NaN          NaN   
2020-10-19  2020-10-19  11.701088  0.363550         NaN          NaN   
2020-10-26  2020-10-26  11.815613  0.367546   11.808067     0.359999   

            casesProbk  deathsProbk  log10cases  log10deaths  log10casesk  \
weekStart                                                                   
2020-09-28         NaN          NaN    4.362520     2.895975     1.009801   
2020-10-05         NaN          NaN    4.381512     2.904716     1.028793   
2020-10-12         NaN          NaN    4.399950     2.909556     1.047231   
2020-10-19         NaN          NaN    4.420945     2.913284     1.068226   
2020-10-26    0.007546     0.007546    4.425175     2.918030     1.072456   

            log10deathsk  newcasesK  newdeathsK  
weekStart                                        
2020-09-28     -0.456744   0.401726    0.000000  
2020-10-05     -0.448004   0.457212    0.007102  
2020-10-12     -0.443163   0.463427    0.003995  
2020-10-19     -0.439435   0.552206    0.003107  
2020-10-26     -0.434689   0.114525    0.003995


bigGroup.tail()


fips       date county       state    cases  deaths  \
2020-09-28  53033.0 2020-10-04   King  Washington  23042.0   787.0   
2020-10-05  53033.0 2020-10-11   King  Washington  24072.0   803.0   
2020-10-12  53033.0 2020-10-18   King  Washington  25116.0   812.0   
2020-10-19  53033.0 2020-10-25   King  Washington  26360.0   819.0   
2020-10-26  53033.0 2020-10-27   King  Washington  26618.0   828.0   

            confirmed_cases  confirmed_deaths  probable_cases  \
2020-09-28              NaN               NaN             NaN   
2020-10-05              NaN               NaN             NaN   
2020-10-12              NaN               NaN             NaN   
2020-10-19              NaN               NaN             NaN   
2020-10-26          26601.0             811.0            17.0   

            probable_deaths  new_cases  new_deaths  POP_ESTIMATE_2019  \
2020-09-28              NaN      905.0         0.0          2252782.0   
2020-10-05              NaN     1030.0        16.0          2252782.0   
2020-10-12              NaN     1044.0         9.0          2252782.0   
2020-10-19              NaN     1244.0         7.0          2252782.0   
2020-10-26             17.0      258.0         9.0          2252782.0   

               weekStr     casesk   deathsk  casesConfk  deathsConfk  \
2020-09-28  2020-09-28  10.228242  0.349346         NaN          NaN   
2020-10-05  2020-10-05  10.685455  0.356448         NaN          NaN   
2020-10-12  2020-10-12  11.148882  0.360443         NaN          NaN   
2020-10-19  2020-10-19  11.701088  0.363550         NaN          NaN   
2020-10-26  2020-10-26  11.815613  0.367546   11.808067     0.359999   

            casesProbk  deathsProbk  log10cases  log10deaths  log10casesk  \
2020-09-28         NaN          NaN    4.362520     2.895975     1.009801   
2020-10-05         NaN          NaN    4.381512     2.904716     1.028793   
2020-10-12         NaN          NaN    4.399950     2.909556     1.047231   
2020-10-19         NaN          NaN    4.420945     2.913284     1.068226   
2020-10-26    0.007546     0.007546    4.425175     2.918030     1.072456   

            log10deathsk  newcasesK  newdeathsK  
2020-09-28     -0.456744   0.401726    0.000000  
2020-10-05     -0.448004   0.457212    0.007102  
2020-10-12     -0.443163   0.463427    0.003995  
2020-10-19     -0.439435   0.552206    0.003107  
2020-10-26     -0.434689   0.114525    0.003995

dfall.tail()


fips       date county       state    cases  deaths  \
2020-09-28  53033.0 2020-10-04   King  Washington  23042.0   787.0   
2020-10-05  53033.0 2020-10-11   King  Washington  24072.0   803.0   
2020-10-12  53033.0 2020-10-18   King  Washington  25116.0   812.0   
2020-10-19  53033.0 2020-10-25   King  Washington  26360.0   819.0   
2020-10-26  53033.0 2020-10-27   King  Washington  26618.0   828.0   

            confirmed_cases  confirmed_deaths  probable_cases  \
2020-09-28              NaN               NaN             NaN   
2020-10-05              NaN               NaN             NaN   
2020-10-12              NaN               NaN             NaN   
2020-10-19              NaN               NaN             NaN   
2020-10-26          26601.0             811.0            17.0   

            probable_deaths  new_cases  new_deaths  POP_ESTIMATE_2019  \
2020-09-28              NaN      905.0         0.0          2252782.0   
2020-10-05              NaN     1030.0        16.0          2252782.0   
2020-10-12              NaN     1044.0         9.0          2252782.0   
2020-10-19              NaN     1244.0         7.0          2252782.0   
2020-10-26             17.0      258.0         9.0          2252782.0   

               weekStr     casesk   deathsk  casesConfk  deathsConfk  \
2020-09-28  2020-09-28  10.228242  0.349346         NaN          NaN   
2020-10-05  2020-10-05  10.685455  0.356448         NaN          NaN   
2020-10-12  2020-10-12  11.148882  0.360443         NaN          NaN   
2020-10-19  2020-10-19  11.701088  0.363550         NaN          NaN   
2020-10-26  2020-10-26  11.815613  0.367546   11.808067     0.359999   

            casesProbk  deathsProbk  log10cases  log10deaths  log10casesk  \
2020-09-28         NaN          NaN    4.362520     2.895975     1.009801   
2020-10-05         NaN          NaN    4.381512     2.904716     1.028793   
2020-10-12         NaN          NaN    4.399950     2.909556     1.047231   
2020-10-19         NaN          NaN    4.420945     2.913284     1.068226   
2020-10-26    0.007546     0.007546    4.425175     2.918030     1.072456   

            log10deathsk  newcasesK  newdeathsK  
2020-09-28     -0.456744   0.401726    0.000000  
2020-10-05     -0.448004   0.457212    0.007102  
2020-10-12     -0.443163   0.463427    0.003995  
2020-10-19     -0.439435   0.552206    0.003107  
2020-10-26     -0.434689   0.114525    0.003995


..

In [51]:
dfall[dfall.deaths.notnull()]

fips       date      county           state  cases  deaths  \
2020-03-23   1001.0 2020-03-29     Autauga         Alabama    6.0     0.0   
2020-03-30   1001.0 2020-04-05     Autauga         Alabama   12.0     0.0   
2020-04-06   1001.0 2020-04-12     Autauga         Alabama   19.0     1.0   
2020-04-13   1001.0 2020-04-19     Autauga         Alabama   27.0     2.0   
2020-04-20   1001.0 2020-04-26     Autauga         Alabama   37.0     2.0   
...             ...        ...         ...             ...    ...     ...   
2020-06-22  78999.0 2020-06-28  VI-Unknown  Virgin Islands    0.0     6.0   
2020-06-29  78999.0 2020-07-05  VI-Unknown  Virgin Islands    0.0     6.0   
2020-07-06  78999.0 2020-07-12  VI-Unknown  Virgin Islands    0.0     6.0   
2020-07-13  78999.0 2020-07-19  VI-Unknown  Virgin Islands    0.0     6.0   
2020-07-20  78999.0 2020-07-22  VI-Unknown  Virgin Islands    0.0     7.0   

            confirmed_cases  confirmed_deaths  probable_cases  \
2020-03-23              NaN               NaN             NaN   
2020-03-30              NaN               NaN             NaN   
2020-04-06              NaN               NaN             NaN   
2020-04-13              NaN               NaN             NaN   
2020-04-20              NaN               NaN             NaN   
...                     ...               ...             ...   
2020-06-22              NaN               NaN             NaN   
2020-06-29              NaN               NaN             NaN   
2020-07-06              NaN               NaN             NaN   
2020-07-13              NaN               NaN             NaN   
2020-07-20              NaN               NaN             NaN   

            probable_deaths  new_cases  new_deaths  POP_ESTIMATE_2019  \
2020-03-23              NaN        0.0         0.0            55869.0   
2020-03-30              NaN        6.0         0.0            55869.0   
2020-04-06              NaN        7.0         1.0            55869.0   
2020-04-13              NaN        8.0         1.0            55869.0   
2020-04-20              NaN       10.0         0.0            55869.0   
...                     ...        ...         ...                ...   
2020-06-22              NaN        0.0         0.0                NaN   
2020-06-29              NaN        0.0         0.0                NaN   
2020-07-06              NaN        0.0         0.0                NaN   
2020-07-13              NaN        0.0         0.0                NaN   
2020-07-20              NaN        0.0         1.0                NaN   

               weekStr    casesk   deathsk  casesConfk  deathsConfk  \
2020-03-23  2020-03-23  0.107394  0.000000         NaN          NaN   
2020-03-30  2020-03-30  0.214788  0.000000         NaN          NaN   
2020-04-06  2020-04-06  0.340081  0.017899         NaN          NaN   
2020-04-13  2020-04-13  0.483273  0.035798         NaN          NaN   
2020-04-20  2020-04-20  0.662264  0.035798         NaN          NaN   
...                ...       ...       ...         ...          ...   
2020-06-22  2020-06-22       NaN       NaN         NaN          NaN   
2020-06-29  2020-06-29       NaN       NaN         NaN          NaN   
2020-07-06  2020-07-06       NaN       NaN         NaN          NaN   
2020-07-13  2020-07-13       NaN       NaN         NaN          NaN   
2020-07-20  2020-07-20       NaN       NaN         NaN          NaN   

            casesProbk  deathsProbk  log10cases  log10deaths  log10casesk  \
2020-03-23         NaN          NaN    0.778151         -inf    -0.969020   
2020-03-30         NaN          NaN    1.079181         -inf    -0.667990   
2020-04-06         NaN          NaN    1.278754     0.000000    -0.468417   
2020-04-13         NaN          NaN    1.431364     0.301030    -0.315807   
2020-04-20         NaN          NaN    1.568202     0.301030    -0.178969   
...                ...          ...         ...          ...          ...   
2020-06-22         NaN          NaN     

In [52]:
dfall.head(6)

fips date   county    state  cases  deaths  confirmed_cases  \
2020-01-20   NaN  NaT  Autauga  Alabama    NaN     NaN              NaN   
2020-01-27   NaN  NaT  Autauga  Alabama    NaN     NaN              NaN   
2020-02-03   NaN  NaT  Autauga  Alabama    NaN     NaN              NaN   
2020-02-10   NaN  NaT  Autauga  Alabama    NaN     NaN              NaN   
2020-02-17   NaN  NaT  Autauga  Alabama    NaN     NaN              NaN   
2020-02-24   NaN  NaT  Autauga  Alabama    NaN     NaN              NaN   

            confirmed_deaths  probable_cases  probable_deaths  new_cases  \
2020-01-20               NaN             NaN              NaN        NaN   
2020-01-27               NaN             NaN              NaN        NaN   
2020-02-03               NaN             NaN              NaN        NaN   
2020-02-10               NaN             NaN              NaN        NaN   
2020-02-17               NaN             NaN              NaN        NaN   
2020-02-24               NaN             NaN              NaN        NaN   

            new_deaths  POP_ESTIMATE_2019 weekStr  casesk  deathsk  \
2020-01-20         NaN            55869.0     NaN     NaN      NaN   
2020-01-27         NaN            55869.0     NaN     NaN      NaN   
2020-02-03         NaN            55869.0     NaN     NaN      NaN   
2020-02-10         NaN            55869.0     NaN     NaN      NaN   
2020-02-17         NaN            55869.0     NaN     NaN      NaN   
2020-02-24         NaN            55869.0     NaN     NaN      NaN   

            casesConfk  deathsConfk  casesProbk  deathsProbk  log10cases  \
2020-01-20         NaN          NaN         NaN          NaN         NaN   
2020-01-27         NaN          NaN         NaN          NaN         NaN   
2020-02-03         NaN          NaN         NaN          NaN         NaN   
2020-02-10         NaN          NaN         NaN          NaN         NaN   
2020-02-17         NaN          NaN         NaN          NaN         NaN   
2020-02-24         NaN          NaN         NaN          NaN         NaN   

            log10deaths  log10casesk  log10deathsk  newcasesK  newdeathsK  
2020-01-20          NaN          NaN           NaN        NaN         NaN  
2020-01-27          NaN          NaN           NaN        NaN         NaN  
2020-02-03          NaN          NaN           NaN        NaN         NaN  
2020-02-10          NaN          NaN           NaN        NaN         NaN  
2020-02-17          NaN          NaN           NaN        NaN         NaN  
2020-02-24          NaN          NaN           NaN        NaN         NaN

#### Back up `df`

* previous step took ~17 minutes to create

In [53]:
dfall.shape
dfbak = dfall.copy()
# dfall = dfbak.copy()

(134193, 26)

In [57]:
df['deathsLag3w'] = df[['deaths']].shift(periods=3)
df.loc[df.fips==53061, ['fips', 'date', 'county', 'cases', 'deaths', 'deathsLag3w']].head(20)
df.loc[df.fips==53061, ['fips', 'date', 'county', 'cases', 'deaths', 'deathsLag3w']].tail(10)
# df.loc[pd.to_datetime('2020-09-28'):pd.to_datetime('2020-10-05'), ['weekStr', 'fips', 'cases', 'deaths', 'deathsLag3w']].tail()

# dfnag = df.loc[~df.fips.isin(['36005', '36047', '36081', '36085']),
#                ['weekStr', 'fips', 'cases', 'deaths', 'deathsLag3w']]\
#           .groupby(['weekStr']).sum().reset_index(drop=False)
# dfnag.loc[pd.to_datetime('2020-09-28'):pd.to_datetime('2020-10-05'), ['weekStr', 'fips', 'cases', 'deaths', 'deathsLag3w']].head()
# dfnag.loc[pd.to_datetime('2020-09-28'):pd.to_datetime('2020-10-05'), ['weekStr', 'fips', 'cases', 'deaths', 'deathsLag3w']].tail()
# dfnag['CFR'] = dfnag['deaths'] / dfnag['cases']
# dfnag['CFRlag3w'] = dfnag['deathsLag3w'] / dfnag['cases']
# dfnag[pd.to_datetime('2020-09-28'):pd.to_datetime('2020-10-05')]
# dfnag[pd.to_datetime('2020-09-28'):pd.to_datetime('2020-10-05')]

fips       date     county  cases  deaths  deathsLag3w
weekStart                                                          
2020-01-20  53061 2020-01-26  Snohomish      1     0.0          1.0
2020-01-27  53061 2020-02-02  Snohomish      1     0.0          1.0
2020-02-03  53061 2020-02-09  Snohomish      1     0.0          1.0
2020-02-10  53061 2020-02-16  Snohomish      1     0.0          0.0
2020-02-17  53061 2020-02-23  Snohomish      1     0.0          0.0
2020-02-24  53061 2020-03-01  Snohomish      2     0.0          0.0
2020-03-02  53061 2020-03-08  Snohomish     36     0.0          0.0
2020-03-09  53061 2020-03-15  Snohomish    175     3.0          0.0
2020-03-16  53061 2020-03-22  Snohomish    480    10.0          0.0
2020-03-23  53061 2020-03-29  Snohomish   1067    23.0          0.0
2020-03-30  53061 2020-04-05  Snohomish   1558    48.0          3.0
2020-04-06  53061 2020-04-12  Snohomish   1866    69.0         10.0
2020-04-13  53061 2020-04-19  Snohomish   2142    92.0         23.0
2020-04-20  53061 2020-04-26  Snohomish   2311   104.0         48.0
2020-04-27  53061 2020-05-03  Snohomish   2737   108.0         69.0
2020-05-04  53061 2020-05-10  Snohomish   2932   116.0         92.0
2020-05-11  53061 2020-05-17  Snohomish   3082   125.0        104.0
2020-05-18  53061 2020-05-24  Snohomish   3240   134.0        108.0
2020-05-25  53061 2020-05-31  Snohomish   3349   147.0        116.0
2020-06-01  53061 2020-06-07  Snohomish   3472   152.0        125.0

fips       date     county  cases  deaths  deathsLag3w
weekStart                                                          
2020-08-24  53061 2020-08-30  Snohomish   7005   220.0        203.0
2020-08-31  53061 2020-09-06  Snohomish   7204   220.0        215.0
2020-09-07  53061 2020-09-13  Snohomish   7385   218.0        218.0
2020-09-14  53061 2020-09-20  Snohomish   7616   221.0        220.0
2020-09-21  53061 2020-09-27  Snohomish   8016   224.0        220.0
2020-09-28  53061 2020-10-04  Snohomish   8283   226.0        218.0
2020-10-05  53061 2020-10-11  Snohomish   8595   229.0        221.0
2020-10-12  53061 2020-10-18  Snohomish   9125   231.0        224.0
2020-10-19  53061 2020-10-25  Snohomish   9659   239.0        226.0
2020-10-26  53061 2020-10-27  Snohomish   9948   241.0        229.0

In [ ]:
fig = px.scatter(dfnag[dfnag.weekStr >= '2020-03-23'], x='weekStr', y='CFR', color='CFR')
fig.data[0].update(mode='markers+lines')
fig.show("notebook")

## Choropleths

### Simple, all-data plots, recent week

In [ ]:
print(df.columns)

#### Case counts (log)

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   decimalRange=[-1, 5],
                   topOfRange=300000.0,
                   colscaleVar='log10cases',
                   zlabel='Total cases',
                   hoverVar='cases',
                   hoverDescription='log10(total cases)',
                   title="Covid-19 Total Cases as of 2020-10-05"
                  )

#### Death counts (log)

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   decimalRange=[-1, 4],
                   topOfRange=25000.0,
                   colscaleVar='log10deaths',
                   zlabel='Total deaths',
                   hoverVar='deaths',
                   hoverDescription='log10(total deaths)',
                   title="Covid-19 Total Deaths as of 2020-10-05"
                  )

#### Cases per 1000 inhabitants (log)

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   decimalRange=[0, 2],
                   topOfRange=170.0,
                   colscaleVar='log10casesk',
                   zlabel='Total cases per 1000',
                   hoverDescription='log10(cases per 1000)',
                   hoverVar='casesk',
                   title="Covid-19 Total Cases per 1000, as of 2020-10-05"
                  )

#### Deaths per 1000 inhabitants (log)

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   decimalRange=[-2, 0],
                   topOfRange=5.2,
                   colscaleVar='log10deathsk',
                   zlabel='Total deaths per 1000',
                   hoverDescription='log10(deaths per 1000)',
                   hoverVar='deathsk',
                   title="Covid-19 Total Deaths per 1000, as of 2020-10-05"
                  )

#### Case counts (linear)

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   linearRange=[0, 25000, 50000, 75000, 100000, 125000],
                   colscaleVar='cases',
                   zlabel='Total cases',
                   hoverVar='cases',
                   hoverDescription='total cases',
                   title="Covid-19 Total Cases as of 2020-10-05"
                  )

#### Death counts

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   linearRange=[0, 2500, 5000, 7500, 10000],
                   colscaleVar='deaths',
                   zlabel='Total deaths',
                   hoverVar='deaths',
                   hoverDescription='total deaths',
                   title="Covid-19 Total Deaths as of 2020-10-05"
                  )

#### Cases per 1000 inhabitants

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   linearRange=[0, 15, 30, 45, 60, 75, 85],
                   colscaleVar='casesk',
                   zlabel='Total cases per 1000',
                   hoverDescription='cases per 1000',
                   hoverVar='casesk',
                   title="Covid-19 Total Cases per 1000, as of 2020-10-05"
                  )

#### Deaths per 1000 inhabitants

In [ ]:
choroplethCovidUSA(df[df.weekStr == '2020-10-05'],
                   counties,
                   linearRange=[0, 0.5, 1, 1.5, 2, 3.5],
                   colscaleVar='deathsk',
                   zlabel='Total deaths per 1000',
                   hoverDescription='deaths per 1000',
                   hoverVar='deathsk',
                   title="Covid-19 Total Deaths per 1000, as of 2020-10-05"
                  )

In [ ]:
dfg[dfg.state=='Colorado'].head()